-- =====================================================================
-- Reference data: skills taxonomy, careers catalogue, sample companies,
-- communities and sample job listings.
-- Companies and jobs are fictional (is_sample = true).
-- Aliases are matched case-insensitively on word boundaries; an alias
-- prefixed with "=" is matched case-sensitively (for short names like R).
-- =====================================================================

insert into public.skills (id, name, category, aliases, learn_hint) values
-- programming & software
('python', 'Python', 'technical', '{python}', 'Work through a Python fundamentals course, then automate one real task you do every week.'),
('r', 'R', 'technical', '{=R,rstudio,tidyverse,ggplot2}', 'Recreate one of your existing analyses in R using the tidyverse.'),
('sql', 'SQL', 'technical', '{sql,mysql,postgresql,postgres,sqlite,t-sql,pl/sql}', 'Practise joins, window functions and CTEs on a public dataset until you can answer business questions without help.'),
('java', 'Java', 'technical', '{java,spring,spring boot}', 'Build a small REST service in Java with Spring Boot and unit tests.'),
('javascript', 'JavaScript', 'technical', '{javascript,js,es6,ecmascript}', 'Build an interactive web page from scratch without a framework, then rebuild it with one.'),
('typescript', 'TypeScript', 'technical', '{typescript}', 'Convert one of your JavaScript projects to TypeScript with strict mode on.'),
('cpp', 'C++', 'technical', '{c++,cpp}', 'Implement classic data structures in modern C++ and benchmark them.'),
('csharp', 'C#', 'technical', '{c#,.net,dotnet,asp.net}', 'Build a small web API with ASP.NET and deploy it.'),
('go', 'Go', 'technical', '{golang,=Go}', 'Write a concurrent command-line tool in Go.'),
('html-css', 'HTML & CSS', 'technical', '{html,css,html5,css3,tailwind,sass}', 'Rebuild a site you like from a screenshot, making it responsive and accessible.'),
('react', 'React', 'technical', '{react,react.js,reactjs,next.js,nextjs}', 'Build and deploy a React app that fetches and displays live data.'),
('nodejs', 'Node.js', 'technical', '{node.js,nodejs,express,express.js}', 'Build a Node.js API with authentication and a database.'),
('rest-apis', 'REST APIs', 'technical', '{rest api,rest apis,restful,api design,fastapi,flask,django,graphql}', 'Design and document a small REST API, then write integration tests for it.'),
('algorithms', 'Data Structures & Algorithms', 'technical', '{algorithms,data structures,leetcode,dynamic programming}', 'Solve two problems a day on a coding practice site, focusing on one topic per week.'),
('software-engineering', 'Software Engineering', 'technical', '{software engineering,unit testing,test-driven,code review,design patterns,object-oriented,oop}', 'Add tests, linting and code review to one of your projects and refactor it for readability.'),
('system-design', 'System Design', 'technical', '{system design,distributed systems,microservices,scalability}', 'Study common system design patterns and sketch designs for three well-known apps.'),
('git', 'Git', 'tool', '{git,github,gitlab,bitbucket,version control}', 'Use Git for every project with meaningful commits, branches and pull requests.'),
('linux', 'Linux', 'tool', '{linux,bash,shell scripting,unix,ubuntu}', 'Use Linux as your daily environment for a month and script your routine tasks in Bash.'),
('docker', 'Docker', 'tool', '{docker,dockerfile,containers,containerization,containerisation}', 'Containerise one of your existing projects and run it with Docker Compose.'),
('kubernetes', 'Kubernetes', 'tool', '{kubernetes,k8s,helm}', 'Deploy a containerised app to a local Kubernetes cluster and scale it.'),
('aws', 'AWS', 'tool', '{aws,amazon web services,ec2,s3,sagemaker,aws lambda}', 'Complete an AWS Cloud Practitioner course and deploy one project on AWS.'),
('azure', 'Microsoft Azure', 'tool', '{azure,microsoft azure}', 'Complete Azure Fundamentals and deploy a small app on Azure.'),
('gcp', 'Google Cloud', 'tool', '{gcp,google cloud,bigquery}', 'Complete a Google Cloud fundamentals path and run a BigQuery analysis.'),
('ci-cd', 'CI/CD', 'tool', '{ci/cd,continuous integration,continuous delivery,github actions,jenkins,gitlab ci}', 'Set up a pipeline that tests and deploys one of your projects on every push.'),
('terraform', 'Infrastructure as Code', 'tool', '{terraform,infrastructure as code,cloudformation,pulumi}', 'Describe a small cloud setup in Terraform and recreate it from scratch.'),
('cloud-architecture', 'Cloud Architecture', 'technical', '{cloud architecture,solution architecture,solutions architecture,cloud design,well-architected}', 'Study a cloud architecture framework and design a solution for a realistic business case.'),
('mlops', 'MLOps', 'technical', '{mlops,mlflow,kubeflow,model deployment,model serving,model monitoring}', 'Deploy one of your models as an API with versioning and basic monitoring.'),
('mobile-dev', 'Mobile Development', 'technical', '{android,ios,swift,kotlin,flutter,react native}', 'Build and publish a small mobile app to a test device.'),
-- data & ai
('statistics', 'Statistics', 'technical', '{statistics,statistical analysis,hypothesis testing,regression,probability,bayesian}', 'Review inference and regression, then apply them to a dataset you care about.'),
('math', 'Mathematics', 'technical', '{linear algebra,calculus,optimization,optimisation,mathematics,stochastic}', 'Refresh linear algebra and probability with a structured course and practice problems.'),
('machine-learning', 'Machine Learning', 'technical', '{machine learning,=ML,supervised learning,unsupervised learning,xgboost}', 'Complete an end-to-end ML project: data cleaning, modelling, evaluation and write-up.'),
('deep-learning', 'Deep Learning', 'technical', '{deep learning,neural networks,neural network,cnn,rnn,transformers,lstm}', 'Train and evaluate a neural network on an image or text dataset.'),
('pytorch', 'PyTorch', 'tool', '{pytorch,torch}', 'Reimplement a classic model in PyTorch and train it on a GPU.'),
('tensorflow', 'TensorFlow', 'tool', '{tensorflow,keras}', 'Build and train a model with Keras, then export it for serving.'),
('scikit-learn', 'scikit-learn', 'tool', '{scikit-learn,sklearn}', 'Build a full scikit-learn pipeline with preprocessing, cross-validation and tuning.'),
('nlp', 'Natural Language Processing', 'technical', '{nlp,natural language processing,text mining,text classification}', 'Fine-tune a language model on a text classification task.'),
('computer-vision', 'Computer Vision', 'technical', '{computer vision,opencv,image classification,object detection,image segmentation}', 'Build an image classifier and explain where it fails.'),
('genai', 'Generative AI & LLMs', 'technical', '{llm,llms,large language models,generative ai,genai,prompt engineering,retrieval-augmented generation}', 'Build a small app that uses an LLM API with retrieval over your own documents.'),
('data-analysis', 'Data Analysis', 'technical', '{data analysis,data analytics,exploratory data analysis,=EDA,analytics}', 'Analyse a public dataset end to end and publish your findings as a short report.'),
('pandas', 'pandas & NumPy', 'tool', '{pandas,numpy}', 'Practise reshaping, grouping and joining data in pandas on messy real-world data.'),
('data-visualization', 'Data Visualisation', 'technical', '{data visualization,data visualisation,matplotlib,seaborn,plotly,d3.js,dashboards,dashboard}', 'Redesign three charts from the news to be clearer, then build a dashboard.'),
('tableau', 'Tableau', 'tool', '{tableau}', 'Build and publish an interactive Tableau Public dashboard.'),
('power-bi', 'Power BI', 'tool', '{power bi,powerbi,dax}', 'Build a Power BI report with a proper data model and a few DAX measures.'),
('excel', 'Excel', 'tool', '{excel,spreadsheets,vba,pivot tables,google sheets}', 'Master lookups, pivot tables and charts by rebuilding a real report.'),
('spark', 'Apache Spark', 'tool', '{spark,pyspark,apache spark,databricks,hadoop}', 'Process a multi-gigabyte dataset with PySpark on a free Databricks workspace.'),
('data-engineering', 'Data Pipelines & ETL', 'technical', '{etl,elt,data pipeline,data pipelines,airflow,dbt,data warehouse,data warehousing,snowflake}', 'Build a scheduled pipeline that loads, cleans and models data into a warehouse.'),
('databases', 'Database Design', 'technical', '{database design,relational databases,data modeling,data modelling,normalization,normalisation}', 'Design a normalised schema for a realistic app and query it.'),
('nosql', 'NoSQL Databases', 'technical', '{nosql,mongodb,dynamodb,redis,cassandra,firestore}', 'Build a feature backed by a document or key-value store and compare it with SQL.'),
('ab-testing', 'A/B Testing', 'technical', '{a/b testing,ab testing,a/b tests,experimentation,experiment design}', 'Design, simulate and analyse an A/B test including power calculations.'),
('time-series', 'Time Series Analysis', 'technical', '{time series,forecasting,arima}', 'Build and backtest a forecasting model on real time series data.'),
('financial-modeling', 'Financial Modelling', 'domain', '{financial modeling,financial modelling,valuation,=DCF,derivatives pricing}', 'Build a three-statement model and a DCF valuation for a listed company.'),
('accounting', 'Accounting & Finance', 'domain', '{accounting,financial analysis,financial statements,budgeting,corporate finance}', 'Learn to read the three financial statements and analyse one annual report.'),
-- security
('cybersecurity', 'Security Fundamentals', 'technical', '{cybersecurity,cyber security,information security,infosec,security+}', 'Study for a security fundamentals certification and set up a home lab.'),
('network-security', 'Network Security', 'technical', '{network security,networking,firewalls,firewall,tcp/ip,=VPN}', 'Build a small home network lab and practise analysing traffic.'),
('siem', 'SIEM & Security Monitoring', 'tool', '{siem,splunk,microsoft sentinel,security monitoring,=SOC}', 'Ingest logs into a free SIEM and write detection rules for common attacks.'),
('incident-response', 'Incident Response', 'technical', '{incident response,threat hunting,digital forensics,=DFIR}', 'Work through incident response scenarios on a blue-team practice platform.'),
('penetration-testing', 'Penetration Testing', 'technical', '{penetration testing,pentesting,ethical hacking,burp suite,metasploit,owasp}', 'Complete beginner rooms on a legal hacking practice platform and write up findings.'),
('risk-compliance', 'Risk & Compliance', 'domain', '{risk management,compliance,iso 27001,governance,=GRC,audit}', 'Map a small organisation against a security or risk framework.'),
('cryptography', 'Cryptography', 'technical', '{cryptography,encryption,=PKI}', 'Learn the core primitives and implement a secure message exchange with a trusted library.'),
-- product, design, business
('ux-research', 'UX Research', 'technical', '{ux research,user research,usability testing,user interviews,personas}', 'Run five user interviews on a product you use and synthesise the insights.'),
('ui-design', 'UI Design', 'technical', '{ui design,visual design,interaction design,prototyping,wireframing,wireframes}', 'Redesign a screen from an app you use and document your decisions.'),
('figma', 'Figma', 'tool', '{figma,adobe xd,sketch app}', 'Build a small design system in Figma with reusable components.'),
('product-management', 'Product Management', 'domain', '{product management,product roadmap,product strategy,user stories,product requirements}', 'Write a one-page product spec for a feature you wish existed and validate it with users.'),
('agile', 'Agile & Scrum', 'domain', '{agile,scrum,kanban,jira,sprint planning}', 'Run your next project in two-week sprints with a simple board and retrospectives.'),
('business-analysis', 'Business Analysis', 'domain', '{business analysis,business analyst,requirements analysis,process mapping,=BPMN,business requirements}', 'Map a real business process end to end and propose improvements.'),
('requirements', 'Requirements Gathering', 'domain', '{requirements gathering,requirements elicitation,stakeholder requirements,user requirements}', 'Interview a stakeholder and turn the conversation into clear, testable requirements.'),
('market-research', 'Market Research', 'domain', '{market research,competitive analysis,market analysis,competitor analysis}', 'Write a short competitive analysis of three products in a market you know.'),
('digital-marketing', 'Digital Marketing', 'domain', '{digital marketing,=SEO,=SEM,social media marketing,google analytics,content marketing}', 'Run a small campaign for a club or side project and measure the results.'),
('project-management', 'Project Management', 'domain', '{project management,=PMP,prince2,project planning,project coordination}', 'Plan and run a small project with a timeline, risks log and status updates.'),
('crm', 'CRM Systems', 'tool', '{=CRM,salesforce,hubspot}', 'Complete a Salesforce or HubSpot beginner trail.'),
('consulting', 'Consulting Methods', 'domain', '{consulting,case interview,case study,problem structuring,business case}', 'Practise structured case interviews with a partner every week.'),
-- soft skills
('communication', 'Communication', 'soft', '{communication,communication skills,written communication,verbal communication}', 'Explain one of your projects to a non-technical friend and refine it until it clicks.'),
('presentation', 'Presentation', 'soft', '{presentation,presentations,public speaking,presenting,presented}', 'Give a short talk at a club, meetup or class and ask for feedback.'),
('teamwork', 'Teamwork', 'soft', '{teamwork,collaboration,collaborated,team player,cross-functional}', 'Join a team project or hackathon and take ownership of one part.'),
('leadership', 'Leadership', 'soft', '{leadership,led a team,team lead,team leader,captain,president}', 'Take on a lead role in a club, project or volunteer group.'),
('problem-solving', 'Problem Solving', 'soft', '{problem solving,problem-solving,analytical thinking,critical thinking}', 'Practise breaking ambiguous problems into structured steps and write down your reasoning.'),
('stakeholder-management', 'Stakeholder Management', 'soft', '{stakeholder management,stakeholder engagement,client management,client-facing,client facing,customer-facing,customer facing}', 'Volunteer for work where you coordinate with people outside your team.'),
('research', 'Research', 'soft', '{research,literature review,research assistant,publication,publications,thesis}', 'Write up one project like a short paper: question, method, results, limitations.'),
('writing', 'Technical Writing', 'soft', '{technical writing,documentation,report writing,blog}', 'Publish a blog post explaining something you learned recently.'),
('mentoring', 'Mentoring & Teaching', 'soft', '{mentoring,mentored,tutoring,tutor,teaching assistant,mentor}', 'Tutor or mentor someone who is one step behind you.'),
('negotiation', 'Negotiation', 'soft', '{negotiation,negotiated}', 'Practise negotiation scenarios and study a classic negotiation framework.');

-- ---------------------------------------------------------------------
-- Careers
-- preference_profile dimensions (1-5): technical, team, research, coding,
-- growth, startup, client — see lib/ai/questionnaire.ts
-- ---------------------------------------------------------------------
insert into public.careers (id, title, field, summary, responsibilities, career_path, preference_profile, traits) values
('data-scientist', 'Data Scientist', 'Data & AI',
 'Uses statistics, machine learning and domain knowledge to turn data into insights and predictive models that guide decisions.',
 '{"Frame business questions as analytical problems","Clean, explore and model large datasets","Build and evaluate predictive models","Communicate findings to stakeholders with clear visualisations"}',
 '{"Data Science Intern","Junior Data Scientist","Data Scientist","Senior Data Scientist","Lead Data Scientist"}',
 '{"technical":4,"team":3,"research":4,"coding":4,"growth":4,"startup":3,"client":2}',
 '{analytical,research,communication,technical_depth}'),
('ml-engineer', 'Machine Learning Engineer', 'Data & AI',
 'Builds, deploys and maintains machine learning systems in production, bridging data science and software engineering.',
 '{"Turn prototype models into reliable production services","Build training and inference pipelines","Monitor model performance and data drift","Collaborate with data scientists and software engineers"}',
 '{"ML Engineering Intern","Junior ML Engineer","ML Engineer","Senior ML Engineer","ML Lead"}',
 '{"technical":5,"team":3,"research":3,"coding":5,"growth":4,"startup":3,"client":1}',
 '{technical_depth,building,cloud}'),
('data-analyst', 'Data Analyst', 'Data & AI',
 'Turns raw data into dashboards, reports and recommendations that help teams make better day-to-day decisions.',
 '{"Write SQL queries to answer business questions","Build and maintain dashboards","Explain what drives key metrics","Present recommendations to non-technical teams"}',
 '{"Data Analyst Intern","Junior Data Analyst","Data Analyst","Senior Data Analyst","Analytics Manager"}',
 '{"technical":3,"team":4,"research":2,"coding":3,"growth":3,"startup":3,"client":3}',
 '{analytical,communication,business}'),
('data-engineer', 'Data Engineer', 'Data & AI',
 'Designs and runs the pipelines and platforms that move, clean and store data so the rest of the company can use it.',
 '{"Build batch and streaming data pipelines","Model data in warehouses and lakes","Keep data quality, reliability and cost under control","Serve the data needs of analysts and scientists"}',
 '{"Data Engineering Intern","Junior Data Engineer","Data Engineer","Senior Data Engineer","Data Platform Lead"}',
 '{"technical":5,"team":3,"research":1,"coding":5,"growth":3,"startup":3,"client":1}',
 '{technical_depth,building,cloud}'),
('research-scientist', 'AI Research Scientist', 'Data & AI',
 'Pushes the state of the art in machine learning through experiments, papers and prototypes that later become products.',
 '{"Read and reproduce recent research","Design and run experiments on new model ideas","Publish findings and present at conferences","Prototype ideas with engineering teams"}',
 '{"Research Intern","Research Assistant","Research Scientist","Senior Research Scientist","Research Lead"}',
 '{"technical":5,"team":2,"research":5,"coding":4,"growth":4,"startup":2,"client":1}',
 '{research,quant,technical_depth}'),
('software-engineer', 'Software Engineer', 'Software',
 'Designs, builds and maintains software products and services used by customers or internal teams.',
 '{"Write clean, tested code for new features","Review code and collaborate in a team","Design APIs and services","Debug and improve performance and reliability"}',
 '{"Software Engineering Intern","Graduate Software Engineer","Software Engineer","Senior Software Engineer","Staff Engineer"}',
 '{"technical":5,"team":4,"research":2,"coding":5,"growth":4,"startup":3,"client":1}',
 '{technical_depth,building}'),
('frontend-developer', 'Frontend Developer', 'Software',
 'Builds the user-facing parts of websites and apps, turning designs into fast, accessible interfaces.',
 '{"Build UI components and pages","Work closely with designers on user experience","Integrate with backend APIs","Optimise performance and accessibility"}',
 '{"Frontend Intern","Junior Frontend Developer","Frontend Developer","Senior Frontend Developer","Frontend Lead"}',
 '{"technical":4,"team":4,"research":1,"coding":5,"growth":4,"startup":4,"client":2}',
 '{building,design}'),
('devops-engineer', 'DevOps / Cloud Engineer', 'Cloud & Infrastructure',
 'Automates how software is built, deployed and run, keeping cloud infrastructure reliable, secure and cost-effective.',
 '{"Build CI/CD pipelines","Manage cloud infrastructure as code","Monitor systems and respond to incidents","Improve reliability and developer experience"}',
 '{"Cloud Intern","Junior DevOps Engineer","DevOps Engineer","Senior DevOps / SRE","Platform Lead"}',
 '{"technical":5,"team":4,"research":1,"coding":4,"growth":3,"startup":3,"client":1}',
 '{cloud,technical_depth}'),
('solutions-architect', 'Solutions Architect', 'Cloud & Infrastructure',
 'Designs technical solutions for customers, translating business needs into cloud architectures and guiding teams through implementation.',
 '{"Understand customer goals and constraints","Design end-to-end cloud architectures","Present and defend technical proposals","Guide implementation teams and review designs"}',
 '{"Graduate Solutions Engineer","Associate Solutions Architect","Solutions Architect","Senior Solutions Architect","Principal Architect"}',
 '{"technical":4,"team":4,"research":2,"coding":2,"growth":4,"startup":2,"client":5}',
 '{technical_depth,communication,cloud,presentation,client_facing}'),
('technology-consultant', 'Technology Consultant', 'Consulting',
 'Helps organisations solve business problems with technology, from analysing processes to recommending and delivering solutions.',
 '{"Interview stakeholders and analyse current processes","Recommend technology solutions","Build business cases and presentations","Support delivery and change management"}',
 '{"Consulting Intern","Graduate Consultant","Consultant","Senior Consultant","Manager"}',
 '{"technical":3,"team":5,"research":2,"coding":2,"growth":4,"startup":2,"client":5}',
 '{communication,client_facing,presentation,analytical,business}'),
('business-analyst', 'Business Analyst', 'Business',
 'Connects business and technology teams by analysing processes, defining requirements and measuring impact.',
 '{"Gather and document requirements","Map and improve business processes","Analyse data to support decisions","Coordinate between stakeholders and delivery teams"}',
 '{"Business Analyst Intern","Junior Business Analyst","Business Analyst","Senior Business Analyst","Delivery Lead"}',
 '{"technical":2,"team":5,"research":2,"coding":1,"growth":3,"startup":2,"client":4}',
 '{analytical,communication,business}'),
('it-project-manager', 'IT Project Manager', 'Business',
 'Plans and delivers technology projects on time and on budget, keeping teams and stakeholders aligned.',
 '{"Plan scope, timelines and budgets","Coordinate delivery teams","Track risks, issues and dependencies","Report progress to stakeholders"}',
 '{"Project Coordinator","Associate Project Manager","Project Manager","Senior Project Manager","Program Manager"}',
 '{"technical":2,"team":5,"research":1,"coding":1,"growth":3,"startup":2,"client":4}',
 '{leadership,communication,business,client_facing}'),
('product-manager', 'Product Manager', 'Product & Design',
 'Decides what a product team builds and why, balancing user needs, business goals and technical constraints.',
 '{"Talk to users and understand their problems","Define product requirements and priorities","Work with engineering and design to ship features","Measure outcomes and iterate"}',
 '{"Associate Product Manager","Product Manager","Senior Product Manager","Group Product Manager","Head of Product"}',
 '{"technical":3,"team":5,"research":2,"coding":1,"growth":5,"startup":4,"client":3}',
 '{communication,business,leadership,analytical}'),
('ux-designer', 'UX/UI Designer', 'Product & Design',
 'Researches how people use products and designs experiences that are useful, usable and delightful.',
 '{"Run user research and usability tests","Create wireframes and interactive prototypes","Design polished interfaces and design systems","Collaborate with product managers and engineers"}',
 '{"Design Intern","Junior UX Designer","UX Designer","Senior Product Designer","Design Lead"}',
 '{"technical":2,"team":4,"research":3,"coding":1,"growth":4,"startup":4,"client":3}',
 '{design,communication,research}'),
('cybersecurity-analyst', 'Cybersecurity Analyst', 'Security',
 'Protects an organisation''s systems and data by monitoring threats, investigating incidents and hardening defences.',
 '{"Monitor alerts and investigate suspicious activity","Respond to and document security incidents","Assess vulnerabilities and recommend fixes","Support security policies and compliance"}',
 '{"Security Intern","SOC Analyst","Cybersecurity Analyst","Senior Security Analyst","Security Lead"}',
 '{"technical":4,"team":3,"research":3,"coding":3,"growth":3,"startup":2,"client":2}',
 '{security,analytical,technical_depth}'),
('quantitative-analyst', 'Quantitative Analyst', 'Finance',
 'Applies maths, statistics and programming to price financial products, manage risk and build trading strategies.',
 '{"Build quantitative models for pricing and risk","Analyse financial time series","Backtest and validate strategies","Explain model results to traders and risk teams"}',
 '{"Quant Intern","Junior Quantitative Analyst","Quantitative Analyst","Senior Quant","Head of Quant"}',
 '{"technical":5,"team":3,"research":4,"coding":4,"growth":4,"startup":2,"client":2}',
 '{quant,analytical,research,technical_depth}');

-- career_id, skill_id, importance (3 = core), target_level (1-3), why
insert into public.career_skills (career_id, skill_id, importance, target_level, why) values
('data-scientist', 'python', 3, 3, 'Python is the main language for data wrangling, modelling and automation.'),
('data-scientist', 'statistics', 3, 3, 'Sound statistics separates real signals from noise and makes results trustworthy.'),
('data-scientist', 'machine-learning', 3, 2, 'Predictive modelling is a core part of most data science roles.'),
('data-scientist', 'sql', 3, 2, 'Most company data lives in SQL databases, so you need to query it yourself.'),
('data-scientist', 'data-analysis', 2, 3, null),
('data-scientist', 'data-visualization', 2, 2, null),
('data-scientist', 'pandas', 2, 2, null),
('data-scientist', 'communication', 2, 2, 'Insights only create value when stakeholders understand and act on them.'),
('data-scientist', 'ab-testing', 1, 2, null),
('data-scientist', 'deep-learning', 1, 1, null),
('data-scientist', 'aws', 1, 1, null),

('ml-engineer', 'python', 3, 3, 'Almost all ML tooling is Python-first.'),
('ml-engineer', 'machine-learning', 3, 3, 'You need to understand models deeply to put them into production safely.'),
('ml-engineer', 'software-engineering', 3, 2, 'Production ML code must be tested, reviewed and maintainable.'),
('ml-engineer', 'docker', 3, 2, 'Containers package models so they run the same way everywhere.'),
('ml-engineer', 'mlops', 3, 2, 'MLOps practices keep models reliable, versioned and monitored after launch.'),
('ml-engineer', 'aws', 2, 2, 'Models are trained and served on cloud infrastructure.'),
('ml-engineer', 'deep-learning', 2, 2, null),
('ml-engineer', 'pytorch', 2, 2, 'PyTorch is the most common framework for building deep learning models.'),
('ml-engineer', 'sql', 2, 2, null),
('ml-engineer', 'git', 2, 2, null),
('ml-engineer', 'statistics', 2, 2, null),
('ml-engineer', 'ci-cd', 1, 1, null),
('ml-engineer', 'kubernetes', 1, 1, null),

('data-analyst', 'sql', 3, 3, 'SQL is the everyday tool for answering business questions with data.'),
('data-analyst', 'excel', 3, 2, 'Spreadsheets remain the common language between analysts and the business.'),
('data-analyst', 'data-analysis', 3, 2, 'Finding what drives a metric is the heart of the role.'),
('data-analyst', 'data-visualization', 3, 2, 'Dashboards and charts are how analysts share insights.'),
('data-analyst', 'communication', 3, 2, 'Analysts must turn numbers into clear recommendations.'),
('data-analyst', 'tableau', 2, 2, null),
('data-analyst', 'statistics', 2, 2, null),
('data-analyst', 'power-bi', 1, 2, null),
('data-analyst', 'python', 2, 1, null),
('data-analyst', 'stakeholder-management', 1, 1, null),
('data-analyst', 'ab-testing', 1, 1, null),

('data-engineer', 'sql', 3, 3, 'Data engineers write and optimise SQL every day.'),
('data-engineer', 'python', 3, 2, 'Python is the glue for pipelines and automation.'),
('data-engineer', 'data-engineering', 3, 2, 'Building reliable pipelines is the core of the job.'),
('data-engineer', 'spark', 2, 2, null),
('data-engineer', 'databases', 2, 2, null),
('data-engineer', 'aws', 2, 2, null),
('data-engineer', 'software-engineering', 2, 2, null),
('data-engineer', 'git', 2, 2, null),
('data-engineer', 'docker', 2, 1, null),
('data-engineer', 'linux', 1, 2, null),
('data-engineer', 'nosql', 1, 1, null),
('data-engineer', 'ci-cd', 1, 1, null),

('research-scientist', 'research', 3, 3, 'The job is doing original research and communicating it rigorously.'),
('research-scientist', 'machine-learning', 3, 3, 'Deep understanding of learning algorithms is expected.'),
('research-scientist', 'deep-learning', 3, 3, 'Most current AI research is in deep learning.'),
('research-scientist', 'math', 3, 3, 'New methods are built on linear algebra, probability and optimisation.'),
('research-scientist', 'python', 3, 2, 'Experiments are implemented in Python.'),
('research-scientist', 'pytorch', 2, 2, null),
('research-scientist', 'statistics', 2, 2, null),
('research-scientist', 'writing', 2, 2, null),
('research-scientist', 'nlp', 1, 2, null),
('research-scientist', 'computer-vision', 1, 2, null),
('research-scientist', 'presentation', 1, 2, null),

('software-engineer', 'algorithms', 3, 2, 'Technical interviews and everyday problem solving rely on data structures and algorithms.'),
('software-engineer', 'software-engineering', 3, 2, 'Testing, code review and clean design are what make code last.'),
('software-engineer', 'git', 3, 2, 'Every engineering team collaborates through version control.'),
('software-engineer', 'javascript', 2, 2, null),
('software-engineer', 'rest-apis', 2, 2, null),
('software-engineer', 'databases', 2, 2, null),
('software-engineer', 'system-design', 2, 1, null),
('software-engineer', 'teamwork', 2, 2, null),
('software-engineer', 'java', 1, 2, null),
('software-engineer', 'python', 1, 2, null),
('software-engineer', 'docker', 1, 1, null),
('software-engineer', 'ci-cd', 1, 1, null),
('software-engineer', 'linux', 1, 1, null),

('frontend-developer', 'javascript', 3, 3, 'JavaScript is the language of the web.'),
('frontend-developer', 'html-css', 3, 3, 'Every interface is built from HTML and CSS.'),
('frontend-developer', 'react', 3, 2, 'React is the most widely used UI library.'),
('frontend-developer', 'typescript', 2, 2, null),
('frontend-developer', 'git', 2, 2, null),
('frontend-developer', 'rest-apis', 2, 2, null),
('frontend-developer', 'software-engineering', 2, 2, null),
('frontend-developer', 'ui-design', 1, 1, null),
('frontend-developer', 'figma', 1, 1, null),
('frontend-developer', 'teamwork', 1, 2, null),

('devops-engineer', 'linux', 3, 3, 'Almost all servers and containers run Linux.'),
('devops-engineer', 'aws', 3, 2, 'Cloud platforms are where the infrastructure lives.'),
('devops-engineer', 'docker', 3, 2, 'Containers are the unit of deployment.'),
('devops-engineer', 'ci-cd', 3, 2, 'Automated pipelines are the core of DevOps.'),
('devops-engineer', 'kubernetes', 2, 2, null),
('devops-engineer', 'terraform', 2, 2, null),
('devops-engineer', 'git', 2, 2, null),
('devops-engineer', 'python', 2, 2, null),
('devops-engineer', 'network-security', 1, 1, null),
('devops-engineer', 'system-design', 1, 1, null),
('devops-engineer', 'incident-response', 1, 1, null),

('solutions-architect', 'cloud-architecture', 3, 2, 'Designing sound cloud solutions is the core deliverable.'),
('solutions-architect', 'aws', 3, 2, 'Architects need hands-on knowledge of at least one major cloud.'),
('solutions-architect', 'communication', 3, 3, 'You translate between business stakeholders and engineers all day.'),
('solutions-architect', 'presentation', 3, 2, 'Architects present and defend proposals to customers.'),
('solutions-architect', 'stakeholder-management', 3, 2, 'The role is customer-facing and relationship driven.'),
('solutions-architect', 'system-design', 2, 2, null),
('solutions-architect', 'requirements', 2, 2, null),
('solutions-architect', 'python', 1, 1, null),
('solutions-architect', 'docker', 1, 1, null),
('solutions-architect', 'databases', 1, 1, null),
('solutions-architect', 'network-security', 1, 1, null),

('technology-consultant', 'communication', 3, 3, 'Consultants are hired to explain problems and solutions clearly.'),
('technology-consultant', 'presentation', 3, 2, 'Recommendations are delivered as presentations to clients.'),
('technology-consultant', 'stakeholder-management', 3, 2, 'Managing client relationships is a daily responsibility.'),
('technology-consultant', 'problem-solving', 3, 2, 'Structuring ambiguous problems is the core consulting skill.'),
('technology-consultant', 'consulting', 2, 2, null),
('technology-consultant', 'business-analysis', 2, 2, null),
('technology-consultant', 'requirements', 2, 2, null),
('technology-consultant', 'teamwork', 2, 2, null),
('technology-consultant', 'data-analysis', 1, 2, null),
('technology-consultant', 'excel', 1, 2, null),
('technology-consultant', 'project-management', 1, 1, null),

('business-analyst', 'business-analysis', 3, 2, 'Analysing and improving processes is the heart of the role.'),
('business-analyst', 'requirements', 3, 2, 'Clear requirements prevent expensive delivery mistakes.'),
('business-analyst', 'stakeholder-management', 3, 2, 'BAs coordinate between many teams and stakeholders.'),
('business-analyst', 'communication', 3, 2, 'You write and present requirements for different audiences.'),
('business-analyst', 'sql', 2, 2, null),
('business-analyst', 'excel', 2, 2, null),
('business-analyst', 'data-analysis', 2, 2, null),
('business-analyst', 'writing', 2, 2, null),
('business-analyst', 'agile', 1, 1, null),
('business-analyst', 'power-bi', 1, 1, null),

('it-project-manager', 'project-management', 3, 2, 'Planning and tracking delivery is the core of the job.'),
('it-project-manager', 'agile', 3, 2, 'Most technology teams deliver in agile iterations.'),
('it-project-manager', 'stakeholder-management', 3, 2, 'Keeping stakeholders aligned is a daily responsibility.'),
('it-project-manager', 'communication', 3, 2, 'Status updates, risks and decisions must be communicated clearly.'),
('it-project-manager', 'leadership', 2, 2, null),
('it-project-manager', 'risk-compliance', 1, 1, null),
('it-project-manager', 'excel', 1, 2, null),
('it-project-manager', 'negotiation', 1, 1, null),

('product-manager', 'product-management', 3, 2, 'Prioritising and specifying what to build is the core of the job.'),
('product-manager', 'communication', 3, 3, 'PMs align engineering, design and business every day.'),
('product-manager', 'stakeholder-management', 3, 2, 'Product decisions involve many stakeholders.'),
('product-manager', 'ux-research', 2, 2, null),
('product-manager', 'data-analysis', 2, 2, null),
('product-manager', 'agile', 2, 2, null),
('product-manager', 'market-research', 2, 2, null),
('product-manager', 'leadership', 2, 2, null),
('product-manager', 'sql', 1, 1, null),
('product-manager', 'ab-testing', 1, 2, null),
('product-manager', 'presentation', 1, 2, null),

('ux-designer', 'ux-research', 3, 2, 'Good design starts from understanding real users.'),
('ux-designer', 'ui-design', 3, 3, 'You will be judged on the quality of your interfaces.'),
('ux-designer', 'figma', 3, 2, 'Figma is the industry-standard design tool.'),
('ux-designer', 'communication', 2, 2, null),
('ux-designer', 'presentation', 2, 2, null),
('ux-designer', 'teamwork', 2, 2, null),
('ux-designer', 'problem-solving', 2, 2, null),
('ux-designer', 'html-css', 1, 1, null),
('ux-designer', 'research', 1, 1, null),

('cybersecurity-analyst', 'cybersecurity', 3, 2, 'Security fundamentals underpin every task in the role.'),
('cybersecurity-analyst', 'network-security', 3, 2, 'Most attacks are detected by understanding network traffic.'),
('cybersecurity-analyst', 'siem', 2, 2, null),
('cybersecurity-analyst', 'incident-response', 2, 2, null),
('cybersecurity-analyst', 'linux', 2, 2, null),
('cybersecurity-analyst', 'risk-compliance', 2, 1, null),
('cybersecurity-analyst', 'communication', 2, 2, null),
('cybersecurity-analyst', 'problem-solving', 2, 2, null),
('cybersecurity-analyst', 'python', 1, 1, null),
('cybersecurity-analyst', 'penetration-testing', 1, 1, null),
('cybersecurity-analyst', 'cryptography', 1, 1, null),

('quantitative-analyst', 'math', 3, 3, 'Pricing and risk models are built on advanced mathematics.'),
('quantitative-analyst', 'statistics', 3, 3, 'Separating real signals from noise in markets is statistical work.'),
('quantitative-analyst', 'python', 3, 2, 'Models and backtests are implemented in code.'),
('quantitative-analyst', 'time-series', 2, 2, null),
('quantitative-analyst', 'financial-modeling', 2, 2, null),
('quantitative-analyst', 'sql', 2, 1, null),
('quantitative-analyst', 'machine-learning', 1, 2, null),
('quantitative-analyst', 'excel', 1, 2, null),
('quantitative-analyst', 'cpp', 1, 1, null),
('quantitative-analyst', 'accounting', 1, 1, null),
('quantitative-analyst', 'communication', 1, 2, null);

-- ---------------------------------------------------------------------
-- Fictional sample companies
-- ---------------------------------------------------------------------
insert into public.companies (slug, name, industry, location, size, description, is_sample) values
('northwind-analytics', 'Northwind Analytics', 'Data & Analytics', 'Sydney, NSW', '200-500', 'A data consultancy helping retailers and banks make sense of their data. (Sample company)', true),
('harbourview-bank', 'Harbourview Bank', 'Financial Services', 'Sydney, NSW', '10,000+', 'A national retail and business bank investing heavily in data and digital. (Sample company)', true),
('lumen-health', 'Lumen Health', 'Health Technology', 'Melbourne, VIC', '50-200', 'Builds software that helps clinics and hospitals coordinate patient care. (Sample company)', true),
('canopy-software', 'Canopy Software', 'Software / SaaS', 'Sydney, NSW', '1,000-5,000', 'Makes collaboration tools used by teams around the world. (Sample company)', true),
('tidewater-cloud', 'Tidewater Cloud', 'Cloud Services', 'Brisbane, QLD', '500-1,000', 'A cloud provider and consultancy helping companies migrate and modernise. (Sample company)', true),
('ironbark-security', 'Ironbark Security', 'Cybersecurity', 'Canberra, ACT', '100-200', 'Provides managed security operations for government and enterprise. (Sample company)', true),
('quokka-labs', 'Quokka Labs', 'AI Startup', 'Sydney, NSW', '10-50', 'An early-stage startup building AI assistants for small businesses. (Sample company)', true),
('meridian-consulting', 'Meridian Consulting', 'Consulting', 'Melbourne, VIC', '5,000+', 'A technology and management consultancy. (Sample company)', true),
('saltbush-capital', 'Saltbush Capital', 'Investment Management', 'Sydney, NSW', '200-500', 'A quantitative investment manager. (Sample company)', true),
('pixel-and-pine', 'Pixel & Pine', 'Design Studio', 'Melbourne, VIC', '20-50', 'A product design studio working with startups and scale-ups. (Sample company)', true);

-- ---------------------------------------------------------------------
-- Communities
-- ---------------------------------------------------------------------
insert into public.communities (slug, kind, name, description, career_id) values
('data-science', 'career', 'Data Science', 'Careers in data science, analytics and statistics.', 'data-scientist'),
('machine-learning', 'career', 'Machine Learning', 'ML engineering, MLOps and applied AI careers.', 'ml-engineer'),
('data-analytics', 'career', 'Data Analytics', 'Analysts, dashboards, SQL and business insight.', 'data-analyst'),
('software-engineering', 'career', 'Software Engineering', 'Building software: interviews, internships and growth.', 'software-engineer'),
('cloud-devops', 'career', 'Cloud & DevOps', 'Cloud, infrastructure, platform and reliability careers.', 'devops-engineer'),
('cybersecurity', 'career', 'Cybersecurity', 'Security operations, pentesting and GRC careers.', 'cybersecurity-analyst'),
('consulting', 'career', 'Consulting', 'Technology and management consulting careers.', 'technology-consultant'),
('product-design', 'career', 'Product & Design', 'Product management, UX and UI design careers.', 'product-manager');

insert into public.communities (slug, kind, name, description, company_id)
select c.slug, 'company', c.name, 'Discuss working at, interviewing with and applying to ' || c.name || '.', c.id
from public.companies c where c.is_sample;

insert into public.communities (slug, kind, name, description) values
('uts', 'university', 'University of Technology Sydney', 'Students and alumni of UTS.'),
('unsw', 'university', 'UNSW Sydney', 'Students and alumni of UNSW.'),
('usyd', 'university', 'The University of Sydney', 'Students and alumni of the University of Sydney.'),
('unimelb', 'university', 'The University of Melbourne', 'Students and alumni of the University of Melbourne.'),
('monash', 'university', 'Monash University', 'Students and alumni of Monash University.'),
('anu', 'university', 'Australian National University', 'Students and alumni of ANU.'),
('graduate-programs', 'topic', 'Graduate Programs', 'Timelines, applications and experiences of graduate programs.'),
('internships', 'topic', 'Internships', 'Finding, applying for and succeeding in internships.'),
('interview-prep', 'topic', 'Interview Prep', 'Technical, behavioural and case interview preparation.');

-- ---------------------------------------------------------------------
-- Sample job listings (fictional companies, no recruiter attached)
-- ---------------------------------------------------------------------
insert into public.jobs (
  company_id, title, location, job_type, industry, career_id, experience_level, education_requirement,
  salary_range, description, responsibilities, requirements, preferred_qualifications,
  required_skills, preferred_skills, grad_years, deadline, is_sample
)
select c.id, j.title, j.location, j.job_type::public.job_type, c.industry, j.career_id, j.experience_level, j.education,
       j.salary, j.description, j.responsibilities, j.requirements, j.preferred,
       j.required_skills, j.preferred_skills, j.grad_years, j.deadline::date, true
from (values
  ('quokka-labs', 'Machine Learning Intern', 'Sydney, NSW', 'internship', 'ml-engineer', 'Student', 'Currently studying Computer Science, Data Science or similar', '$38-$42 per hour',
   'Join a small team shipping AI assistants to real customers. You will help take models from notebooks to production.',
   '{"Prototype and evaluate ML models","Help package models as APIs","Write tests and documentation for ML code"}'::text[],
   '{"Solid Python skills","Understanding of core machine learning concepts","Experience with PyTorch or a similar framework"}'::text[],
   '{"Exposure to AWS or another cloud","Experience with Docker"}'::text[],
   '{python,machine-learning,pytorch}'::text[], '{aws,docker,mlops}'::text[], '{2026,2027}'::int[], '2026-11-15'),
  ('harbourview-bank', 'Graduate Data Scientist', 'Sydney, NSW', 'graduate', 'data-scientist', 'Graduate', 'Bachelor or Master in a quantitative field', '$85,000-$95,000',
   'Rotate through the bank''s data science teams working on credit risk, customer analytics and fraud detection.',
   '{"Build and validate predictive models","Analyse large customer datasets with SQL and Python","Present insights to business stakeholders"}'::text[],
   '{"Strong Python and SQL","Good grounding in statistics","Machine learning project experience"}'::text[],
   '{"Experience communicating results to non-technical audiences","A/B testing knowledge"}'::text[],
   '{python,sql,statistics,machine-learning}'::text[], '{data-visualization,communication,ab-testing}'::text[], '{2026,2027}'::int[], '2026-10-31'),
  ('northwind-analytics', 'Data Analyst Intern', 'Sydney, NSW', 'internship', 'data-analyst', 'Student', 'Currently studying any degree with a quantitative component', '$35 per hour',
   'Help our clients understand their customers by building reports and dashboards.',
   '{"Write SQL queries against client data","Build dashboards","Summarise findings for consultants"}'::text[],
   '{"SQL fundamentals","Confident with Excel","An eye for clear charts"}'::text[],
   '{"Tableau or Power BI","Basic Python"}'::text[],
   '{sql,excel,data-visualization}'::text[], '{tableau,python,communication}'::text[], '{2027,2028}'::int[], '2026-12-01'),
  ('tidewater-cloud', 'Junior Data Engineer', 'Brisbane, QLD', 'full_time', 'data-engineer', 'Entry level (0-2 years)', 'Degree in Computer Science, IT or similar', '$90,000-$105,000',
   'Build the pipelines that move our customers'' data into modern cloud warehouses.',
   '{"Develop and maintain ETL pipelines","Model data in the warehouse","Monitor data quality"}'::text[],
   '{"Strong SQL","Python for data processing","Understanding of data pipelines"}'::text[],
   '{"Spark or Databricks","AWS experience","Docker"}'::text[],
   '{sql,python,data-engineering}'::text[], '{spark,aws,docker}'::text[], '{2025,2026}'::int[], '2026-11-30'),
  ('canopy-software', 'Graduate Machine Learning Engineer', 'Sydney, NSW', 'graduate', 'ml-engineer', 'Graduate', 'Bachelor or Master in Computer Science, Data Science or similar', '$100,000-$115,000',
   'Work on the ML platform behind search and recommendations used by millions of people.',
   '{"Productionise and monitor ML models","Improve training pipelines","Collaborate with product engineers"}'::text[],
   '{"Strong Python","Machine learning fundamentals","Software engineering practices","Docker"}'::text[],
   '{"AWS or GCP","MLOps tooling","Kubernetes"}'::text[],
   '{python,machine-learning,software-engineering,docker}'::text[], '{aws,mlops,kubernetes}'::text[], '{2026,2027}'::int[], '2026-10-20'),
  ('canopy-software', 'Software Engineering Intern', 'Sydney, NSW', 'internship', 'software-engineer', 'Student', 'Penultimate-year Computer Science or Software Engineering student', '$45 per hour',
   'Spend 12 weeks shipping real features with one of our product teams.',
   '{"Build and test product features","Participate in code reviews","Present your project at the end of the internship"}'::text[],
   '{"Data structures and algorithms","Git","JavaScript or another modern language"}'::text[],
   '{"React","REST APIs","Database experience"}'::text[],
   '{algorithms,git,javascript}'::text[], '{react,rest-apis,databases}'::text[], '{2027,2028}'::int[], '2026-09-30'),
  ('lumen-health', 'Graduate Software Engineer', 'Melbourne, VIC', 'graduate', 'software-engineer', 'Graduate', 'Degree in Software Engineering or Computer Science', '$88,000-$98,000',
   'Help build software that clinicians rely on every day.',
   '{"Develop backend services in Java","Write automated tests","Work in an agile team"}'::text[],
   '{"Software engineering fundamentals","Algorithms","Java","Git"}'::text[],
   '{"REST API design","SQL databases","CI/CD"}'::text[],
   '{software-engineering,algorithms,java,git}'::text[], '{rest-apis,databases,ci-cd}'::text[], '{2026}'::int[], '2026-11-10'),
  ('pixel-and-pine', 'Frontend Developer', 'Melbourne, VIC', 'full_time', 'frontend-developer', 'Junior (1-2 years)', 'Degree or equivalent portfolio', '$85,000-$100,000',
   'Turn our designers'' work into polished, accessible web apps for startup clients.',
   '{"Build responsive UIs in React","Work closely with designers","Maintain our component library"}'::text[],
   '{"JavaScript","HTML & CSS","React"}'::text[],
   '{"TypeScript","Figma","An eye for UI detail"}'::text[],
   '{javascript,html-css,react}'::text[], '{typescript,figma,ui-design}'::text[], '{2024,2025,2026}'::int[], '2026-12-15'),
  ('tidewater-cloud', 'Cloud Engineer Intern', 'Brisbane, QLD', 'internship', 'devops-engineer', 'Student', 'Currently studying IT, Computer Science or Engineering', '$40 per hour',
   'Help customers move to the cloud and automate their infrastructure.',
   '{"Automate infrastructure tasks","Support cloud migrations","Document runbooks"}'::text[],
   '{"Linux basics","AWS fundamentals","Python or Bash scripting"}'::text[],
   '{"Docker","Terraform","CI/CD pipelines"}'::text[],
   '{linux,aws,python}'::text[], '{docker,terraform,ci-cd}'::text[], '{2027,2028}'::int[], '2026-11-01'),
  ('tidewater-cloud', 'Associate Solutions Architect', 'Sydney, NSW', 'graduate', 'solutions-architect', 'Graduate', 'Degree in a technical discipline', '$95,000-$110,000',
   'Work with customers to design cloud solutions and present them to technical and business audiences.',
   '{"Run discovery sessions with customers","Design cloud architectures","Present proposals and demos"}'::text[],
   '{"AWS knowledge","Understanding of cloud architecture","Excellent communication and presentation skills"}'::text[],
   '{"System design","Stakeholder management","Some programming experience"}'::text[],
   '{aws,cloud-architecture,communication,presentation}'::text[], '{system-design,stakeholder-management,python}'::text[], '{2026,2027}'::int[], '2026-10-25'),
  ('meridian-consulting', 'Graduate Technology Consultant', 'Melbourne, VIC', 'graduate', 'technology-consultant', 'Graduate', 'Any degree', '$80,000-$90,000',
   'Help clients across industries solve business problems with technology.',
   '{"Interview client stakeholders","Analyse processes and data","Prepare client presentations"}'::text[],
   '{"Strong communication","Structured problem solving","Comfortable working with clients"}'::text[],
   '{"Business analysis","Data analysis","Presentation skills"}'::text[],
   '{communication,problem-solving,stakeholder-management}'::text[], '{business-analysis,data-analysis,presentation}'::text[], '{2026,2027}'::int[], '2026-10-15'),
  ('harbourview-bank', 'Business Analyst (Part-time)', 'Sydney, NSW', 'part_time', 'business-analyst', 'Student or entry level', 'Currently studying Business, IT or similar', '$40 per hour',
   'Support a digital banking team by documenting requirements and analysing processes, 2-3 days per week.',
   '{"Document business requirements","Map current processes","Support user acceptance testing"}'::text[],
   '{"Business analysis","Requirements gathering","Excel"}'::text[],
   '{"SQL","Agile","Stakeholder management"}'::text[],
   '{business-analysis,requirements,excel}'::text[], '{sql,agile,stakeholder-management}'::text[], '{2026,2027,2028}'::int[], '2026-12-20'),
  ('canopy-software', 'Associate Product Manager', 'Sydney, NSW', 'graduate', 'product-manager', 'Graduate', 'Any degree', '$95,000-$105,000',
   'Learn product management by owning a small area of a product used by millions.',
   '{"Talk to users and analyse feedback","Write product specs","Work with engineering and design to ship"}'::text[],
   '{"Product thinking","Strong communication","Comfortable with data"}'::text[],
   '{"UX research","Agile","SQL"}'::text[],
   '{product-management,communication,data-analysis}'::text[], '{ux-research,agile,sql}'::text[], '{2026,2027}'::int[], '2026-11-05'),
  ('pixel-and-pine', 'UX Design Intern', 'Melbourne, VIC', 'internship', 'ux-designer', 'Student', 'Studying design, HCI or similar', '$35 per hour',
   'Work on real client projects from research to high-fidelity prototypes.',
   '{"Assist with user research","Create wireframes and prototypes","Present design decisions"}'::text[],
   '{"Figma","UI design fundamentals","User research basics"}'::text[],
   '{"HTML & CSS","Presentation skills"}'::text[],
   '{figma,ui-design,ux-research}'::text[], '{html-css,presentation}'::text[], '{2027,2028}'::int[], '2026-11-20'),
  ('ironbark-security', 'Graduate SOC Analyst', 'Canberra, ACT', 'graduate', 'cybersecurity-analyst', 'Graduate', 'Degree in Cybersecurity, IT or similar', '$80,000-$90,000',
   'Monitor and respond to threats for government and enterprise customers.',
   '{"Triage security alerts","Investigate incidents","Write incident reports"}'::text[],
   '{"Security fundamentals","Networking","Linux"}'::text[],
   '{"SIEM experience","Incident response","Python scripting"}'::text[],
   '{cybersecurity,network-security,linux}'::text[], '{siem,incident-response,python}'::text[], '{2026,2027}'::int[], '2026-10-30'),
  ('saltbush-capital', 'Quantitative Analyst Intern', 'Sydney, NSW', 'internship', 'quantitative-analyst', 'Student', 'Studying Mathematics, Statistics, Physics or Computer Science', '$55 per hour',
   'Research and backtest systematic investment strategies alongside our quant team.',
   '{"Analyse financial time series","Backtest strategies","Present research findings"}'::text[],
   '{"Python","Statistics","Strong mathematics"}'::text[],
   '{"Time series analysis","Financial modelling","C++"}'::text[],
   '{python,statistics,math}'::text[], '{time-series,financial-modeling,cpp}'::text[], '{2027,2028}'::int[], '2026-10-10'),
  ('quokka-labs', 'Research Assistant, NLP', 'Remote (Australia)', 'part_time', 'research-scientist', 'Student', 'Master or PhD student in AI or related field', '$45 per hour',
   'Run experiments on small language models for business document understanding.',
   '{"Reproduce recent NLP papers","Run and analyse experiments","Write internal research notes"}'::text[],
   '{"Python","NLP","Deep learning","Research experience"}'::text[],
   '{"PyTorch","Technical writing"}'::text[],
   '{python,nlp,deep-learning,research}'::text[], '{pytorch,writing}'::text[], '{2026,2027}'::int[], '2026-12-31'),
  ('lumen-health', 'Data Scientist', 'Melbourne, VIC', 'full_time', 'data-scientist', 'Junior (1-3 years)', 'Degree in a quantitative field', '$105,000-$120,000',
   'Use clinical and operational data to help hospitals plan capacity and improve patient outcomes.',
   '{"Build forecasting and classification models","Partner with clinicians on analysis","Communicate results clearly"}'::text[],
   '{"Python","Statistics","Machine learning","SQL"}'::text[],
   '{"Deep learning","Communication skills","AWS"}'::text[],
   '{python,statistics,machine-learning,sql}'::text[], '{deep-learning,communication,aws}'::text[], '{2024,2025,2026}'::int[], '2026-12-10'),
  ('northwind-analytics', 'Analytics Graduate', 'Sydney, NSW', 'graduate', 'data-analyst', 'Graduate', 'Any degree with a quantitative component', '$75,000-$85,000',
   'Join our graduate program and work with retail and banking clients on analytics projects.',
   '{"Analyse client data","Build reports and dashboards","Present insights to clients"}'::text[],
   '{"SQL","Data analysis","Communication"}'::text[],
   '{"Power BI","Python","Stakeholder management"}'::text[],
   '{sql,data-analysis,communication}'::text[], '{power-bi,python,stakeholder-management}'::text[], '{2026,2027}'::int[], '2026-10-28'),
  ('meridian-consulting', 'IT Project Coordinator', 'Sydney, NSW', 'full_time', 'it-project-manager', 'Entry level (0-2 years)', 'Any degree', '$75,000-$85,000',
   'Support delivery of technology projects for our clients.',
   '{"Maintain project plans and RAID logs","Coordinate meetings and status reports","Support project managers"}'::text[],
   '{"Project management basics","Communication","Agile"}'::text[],
   '{"Stakeholder management","Excel"}'::text[],
   '{project-management,communication,agile}'::text[], '{stakeholder-management,excel}'::text[], '{2025,2026}'::int[], '2026-11-25')
) as j(company_slug, title, location, job_type, career_id, experience_level, education, salary, description,
       responsibilities, requirements, preferred, required_skills, preferred_skills, grad_years, deadline)
join public.companies c on c.slug = j.company_slug;
