-- Real job listings collected from public job ads (is_sample = false).
-- Company names not given in the ad are fictional.

insert into public.companies (slug, name, industry, location, description, is_sample) values
('jd-medical-imaging-research', 'Southgate Imaging Lab', 'Higher Education / Research', null, 'A university research group developing real-time image guidance for the thorax and abdomen.', false),
('rivkin', 'Rivkin', 'Financial Services', null, 'An established Australian financial-services firm.', false),
('anduril-australia', 'Anduril Australia', 'Defence Technology', null, 'Builds autonomous platforms and mission software for defence.', false),
('air-liquide-healthcare', 'Air Liquide Healthcare', 'Healthcare', null, 'Healthcare division of Air Liquide.', false),
('jd-fullstack-saas', 'Brightwattle', 'Software / SaaS', null, null, false),
('jd-helensvale-proptech', 'Coastline Ledger', 'Software / Fintech', 'Helensvale, QLD', 'A small, profitable, Australian-owned software business with a 20-year customer base.', false),
('jd-trading-tech', 'Kestrel Markets', 'Financial Markets', null, null, false),
('jd-energy-tech', 'Gridline Energy', 'Energy', null, null, false),
('jd-lab-calibration', 'Calibre Instruments', 'Scientific Instruments / SaaS', null, null, false),
('jd-cloud-platform', 'Stratus Works', 'Software', null, null, false),
('jd-integration-services', 'Linkbridge Integration', 'IT Services', null, null, false),
('jd-data-startup', 'Numbat Data', 'Data & Analytics', null, null, false),
('jd-web-agency', 'Wattle Web Studio', 'Digital / Web', null, null, false),
('jd-mining-saas', 'Redrock Field Systems', 'Mining Technology', null, null, false),
('jd-business-software', 'Bluegum Software', 'Software', null, null, false),
('jd-data-platform', 'Clearstream Data', 'Data & AI', null, null, false),
('jd-fullstack-cloud', 'Nimbus Harbour', 'Software', null, null, false),
('jd-healthtech-software', 'Carewell Health Tech', 'Health Technology', null, null, false),
('jd-web-platform', 'Ferntree Digital', 'Software', null, null, false),
('jd-enterprise-java', 'Ironwood Systems', 'IT Services', null, null, false),
('jd-microsoft-partner', 'Blue Harbour Consulting', 'IT Consulting', null, null, false)
on conflict (slug) do nothing;

insert into public.jobs (
  company_id, title, location, job_type, industry, career_id, experience_level, education_requirement,
  salary_range, description, responsibilities, requirements, preferred_qualifications,
  required_skills, preferred_skills, grad_years, is_sample
)
select c.id, j.title, j.location, j.job_type::public.job_type, c.industry, j.career_id, j.experience_level, j.education,
       j.salary, j.description, j.responsibilities, j.requirements, j.preferred,
       j.required_skills, j.preferred_skills, j.grad_years, false
from (values
  ('jd-medical-imaging-research', 'Software Engineer (Medical Imaging Research)', null, 'full_time', 'software-engineer', 'Experienced', 'Masters in Software Engineering, IT, Computer Science or a related discipline', null, 'Lead software development for cutting-edge real-time image guidance of the thorax and abdomen within a grant-funded research team.', array['Lead the development and maintenance of software for real-time image guidance of the thorax and abdomen', 'Curate databases and code central to the aims of the grant', 'Author high-impact publications and present at international conferences', 'Support students and junior researchers', 'Develop scalable, performant software solutions', 'Coordinate architectural design and system planning for software projects', 'Oversee testing and implement automated testing frameworks', 'Coordinate deployment pipelines', 'Create and maintain technical documentation', 'Monitor risk, promote workplace health and safety and ensure alignment with university policies']::text[], array['Masters in Software Engineering, IT, Computer Science or a related discipline', 'Experience with medical imaging or devices', 'Experience integrating novel technologies with clinical systems', 'Experience with testing frameworks and front-end and back-end web development', 'Experience delivering solutions in an Agile/Scrum environment', 'Unrestricted Australian work rights (no visa sponsorship)']::text[], array['Recognition through awards and scholarships']::text[], array['software-engineering', 'ci-cd', 'agile', 'research']::text[], array['computer-vision', 'writing', 'mentoring']::text[], '{}'::int[]),
  ('rivkin', 'Junior Software Engineer', null, 'full_time', 'software-engineer', 'Junior (1+ years)', 'Degree in Computer Science, Software Engineering, Information Systems or related (Master''s preferred)', '$75,000-$85,000 + super', 'Design, build and maintain the internal software systems and integrations behind Rivkin''s day-to-day operations, reporting to the Head of IT and working with non-technical stakeholders.', array['Design, develop, deploy and maintain internal web applications, marketing sites and operational tooling, including hosting and deployment pipelines', 'Translate business requirements from non-technical stakeholders into technical specifications and production systems', 'Integrate internal systems with external platforms and APIs (financial-services providers, Microsoft 365, Notion, ActiveCampaign, Twilio, Cloudflare)', 'Maintain, document and improve existing systems', 'Produce technical documentation and operational procedures']::text[], array['1+ year of professional software development and systems integration experience', 'Full-stack capability across JavaScript/TypeScript, Python, Bash and SQL', 'Experience integrating third-party APIs and SaaS platforms', 'Ability to deliver documented end-to-end solutions from ambiguous requirements', 'Experience operating production systems on cloud/VPS infrastructure (Git/GitHub, deployment pipelines, Cloudflare)', 'Strong written and verbal English communication']::text[], array['Tertiary qualification in a computing discipline (Master''s preferred)', 'Exposure to financial services (stockbroking, wealth, SMSF or similar)', 'Experience writing technical documentation for non-technical audiences']::text[], array['javascript', 'typescript', 'python', 'sql', 'linux', 'rest-apis', 'git', 'ci-cd', 'communication']::text[], array['writing', 'requirements', 'accounting']::text[], '{}'::int[]),
  ('anduril-australia', 'Software Engineer', null, 'full_time', 'software-engineer', 'Experienced', 'Bachelor''s in Robotics, Mechatronics, Computer Science, Engineering or equivalent experience', null, 'Deliver software across autonomy, simulation, data processing, payload integration and command-and-control for next-generation autonomous platforms, owning outcomes through the full product lifecycle.', array['Build solutions that balance end-user needs with constraints in a multi-stakeholder environment', 'Own software deployed to customers', 'Develop reusable software components across product lines', 'Develop software that runs on and off robotic platforms', 'Develop and iteratively enhance vehicle and mission software, including testing, monitoring and operation', 'Create software- and hardware-in-the-loop test and simulation fixtures', 'Support vehicle manufacturing and deployment', 'Travel to co-locate with end-users or other teams up to 20% of the time']::text[], array['Bachelor''s in Robotics, Mechatronics, Computer Science, Engineering or equivalent experience', 'Professional experience as a Software Engineer', 'Systems/application programming skills: algorithms, data structures, concurrency, scaling, testing and design', 'Experience troubleshooting remotely deployed software systems', 'Ability to obtain and maintain an Australian Government Security Clearance']::text[], array['Experience delivering a military mission system', 'Backend or embedded software in C++, Rust and/or Go', 'Frontend applications in TypeScript and React', 'Horizontally scaled cloud technologies', 'Embedded software for robotics', 'Modelling and simulation', 'High-assurance safety-critical software', 'Familiarity with Systems Engineering concepts']::text[], array['software-engineering', 'algorithms', 'system-design']::text[], array['cpp', 'go', 'typescript', 'react', 'cloud-architecture']::text[], '{}'::int[]),
  ('air-liquide-healthcare', 'IT Systems & Database Analyst', null, 'full_time', 'software-engineer', null, null, null, 'Support and improve business-critical systems including MS Dynamics GP and SQL databases, act as first point of contact for internal IT issues and support the upcoming ERP migration.', array['Support and monitor MS Dynamics GP, SQL databases, reporting tools and integrations', 'Act as first point of contact for internal IT and system issues', 'Coordinate with the external IT provider on tickets, servers, patching and updates', 'Maintain SQL databases, queries, views, stored procedures, reports and backup schedules', 'Automate processes with SQL, PowerShell, APIs, CSV and JSON', 'Support API integrations and data imports/exports', 'Assist with Power BI dashboards and KPI reporting', 'Support global IT teams with the upcoming ERP migration', 'Maintain documentation of databases, integrations and procedures']::text[], array['Strong MS Dynamics Great Plains experience', 'Strong SQL database administration and reporting experience', 'Programming skills', 'Experience with APIs, data integrations, CSV, XML, JSON and automation tools', 'Good understanding of ERP and business systems', 'Strong troubleshooting, communication and problem-solving skills', 'Ability to work independently and manage priorities']::text[], array['ERP experience', 'Power BI skills']::text[], array['sql', 'databases', 'rest-apis', 'problem-solving', 'communication']::text[], array['power-bi', 'writing']::text[], '{}'::int[]),
  ('jd-fullstack-saas', 'Full-Stack Software Engineer (TypeScript/React)', null, 'full_time', 'software-engineer', 'Mid-level (3+ years)', null, null, 'Build full-stack features on a distributed microservices platform using TypeScript and React, with strong testing and ownership in production.', '{}'::text[], array['3+ years developing applications with TypeScript and React', 'Strong full-stack fundamentals and experience with distributed microservices', 'Disciplined engineering practices: unit and integration testing, code review, security and reliability', 'Strong problem-solving and trade-off analysis', 'Ownership mindset, supporting solutions in production', 'Excellent communication and collaboration']::text[], array['Experience with, or curiosity about, generative AI tools in software development']::text[], array['typescript', 'react', 'system-design', 'software-engineering', 'problem-solving']::text[], array['genai', 'communication']::text[], '{}'::int[]),
  ('jd-helensvale-proptech', 'Graduate Software Developer', 'Helensvale, QLD', 'graduate', 'software-engineer', 'Graduate', 'Recent graduate in Computer Science, Software Engineering, IT or similar (or completing at end of 2026)', null, 'Join a small in-office team building property and accounting software, using AI-assisted development with direct mentoring from experienced developers. 100% on-site in Helensvale.', '{}'::text[], array['Recent graduate in Computer Science, Software Engineering, IT or similar, or completing your degree at the end of 2026', 'Demonstrable fluency with AI-assisted development (e.g. Claude Code)', 'Solid fundamentals in C# or a similar object-oriented language, plus SQL', 'Some exposure to modern front-end development (React, Angular, TypeScript or Blazor)', 'Judgement to know when AI output is wrong', 'On-site every day in Helensvale', 'Australian citizen or permanent resident (no visa sponsorship)', 'Clear written and verbal English communication']::text[], array['Personal projects, GitHub profile, internships, hackathons or freelance work', 'Exposure to Microsoft Azure', 'Interest in property, accounting or fintech']::text[], array['csharp', 'sql', 'genai', 'software-engineering', 'communication']::text[], array['react', 'typescript', 'azure', 'git']::text[], '{2025,2026}'::int[]),
  ('jd-trading-tech', 'Software Engineer (Financial Markets)', null, 'full_time', 'software-engineer', null, 'Degree in a STEM subject or equivalent', null, 'Build performance-sensitive software for financial markets as part of a pragmatic, quantitative engineering team.', '{}'::text[], array['Strong understanding of algorithms and data structures', 'Knowledge of at least one mainstream OOP language (C++, C#, Java, JavaScript, Go)', 'Degree in a STEM subject or equivalent', 'Interest in financial markets']::text[], array['C++', 'Asynchronous and multi-threaded programming', 'Clean, readable, testable code', 'Networks and network programming', 'Computer architecture and its impact on performance', 'Python, shell scripting, CMake, Jenkins, PCAP/Wireshark, C, static analysers']::text[], array['algorithms', 'software-engineering', 'math']::text[], array['cpp', 'python', 'linux', 'network-security', 'ci-cd']::text[], '{}'::int[]),
  ('jd-energy-tech', 'Software Engineer (Python/AWS)', null, 'full_time', 'software-engineer', null, 'Computer science qualification or related discipline, or equivalent experience', null, 'Deliver features end-to-end on a Python-based AWS platform using containerised and serverless infrastructure, working with senior engineers and energy-market domain experts.', array['Deliver features end-to-end from requirements to production', 'Contribute to an AWS platform using containerised and serverless infrastructure', 'Support and troubleshoot live applications', 'Contribute to design, tooling and architecture decisions']::text[], array['Experience shipping high-quality software to production', 'Application design fundamentals, including REST APIs and SQL databases', 'Eagerness to build on a Python-based AWS stack', 'Computer science qualification or related discipline, or equivalent experience']::text[], array['Asynchronous Python in production (e.g. FastAPI) and typed models (e.g. Pydantic)', 'Experience building data pipelines or maintaining live applications', 'Interest in energy markets, price forecasting or mathematical optimisation']::text[], array['python', 'aws', 'rest-apis', 'sql', 'docker']::text[], array['data-engineering', 'time-series', 'math']::text[], '{}'::int[]),
  ('jd-lab-calibration', 'Full-Stack Software Engineer (.NET/Angular)', null, 'full_time', 'software-engineer', 'Mid-level (2+ years)', 'Diploma, Bachelor''s or Master''s in Computer Science, Software Engineering or related', null, 'Lead delivery of a full-stack SaaS platform connecting precision laboratory equipment to the cloud, from architecture through CI/CD, security and code review.', array['Design scalable, secure software architectures for web and mobile', 'Build APIs and data-processing layers connecting laboratory equipment to the cloud', 'Write clean, documented code across frontend, backend and database', 'Refactor legacy code', 'Lead delivery from scoping and estimation to deployment', 'Prioritise the backlog within an Agile framework', 'Review mock-ups with the Product Designer for technical feasibility', 'Oversee CI/CD pipelines and automated testing', 'Protect sensitive calibration data and ensure regulatory compliance', 'Conduct code reviews']::text[], array['2+ years in software engineering, focused on full-stack SaaS', 'Experience managing complex projects and making architectural decisions', 'Experience with .NET (backend), Angular (frontend), Python and API development', 'Experience with AI and development tools (Claude, GitHub, Figma, VS Code, Postman)', 'Diploma, Bachelor''s or Master''s in Computer Science, Software Engineering or related', 'Experience in Scrum or Kanban environments']::text[], array['Hardware-to-cloud data integration or IoT software', 'Cloud certifications (Azure or AWS Solutions Architect)']::text[], array['csharp', 'typescript', 'python', 'rest-apis', 'ci-cd', 'system-design', 'agile']::text[], array['azure', 'aws', 'cloud-architecture', 'mobile-dev', 'genai']::text[], '{}'::int[]),
  ('jd-cloud-platform', 'Software Engineer (React/Python)', null, 'full_time', 'software-engineer', null, 'Degree in Computer Science, IT, Engineering or equivalent experience', null, 'Build front-end applications and Python automation on a cloud platform managed with Infrastructure as Code.', '{}'::text[], array['Degree in Computer Science, IT, Engineering or equivalent experience', 'Experience developing front-end applications with React and TypeScript', 'Strong Python development and automation skills', 'Experience with databases, SQL and data troubleshooting', 'Knowledge of Infrastructure as Code (Terraform or OpenTofu)']::text[], '{}'::text[], array['react', 'typescript', 'python', 'sql', 'terraform']::text[], '{}'::text[], '{}'::int[]),
  ('jd-integration-services', 'Integration Developer', null, 'full_time', 'software-engineer', 'Junior (1-3 years)', 'Degree in IT, Computer Science, Software Engineering or related', null, 'Develop and support system integrations, APIs and connectors, including data mappings and transformations between systems.', array['Develop and maintain system integrations, APIs and connectors', 'Configure, test and support integration processes', 'Build data mappings and transformation logic', 'Monitor integration performance and investigate issues', 'Support troubleshooting, root cause analysis and incident resolution', 'Participate in technical design, code reviews and delivery', 'Work with JSON, XML, CSV and database records', 'Maintain technical documentation']::text[], array['Degree in IT, Computer Science, Software Engineering or related', '1-3 years in software development, integration development or application support', 'Understanding of API and integration concepts', 'Exposure to REST APIs, JSON, XML and SQL', 'Strong analytical and problem-solving skills', 'Excellent communication and stakeholder engagement']::text[], '{}'::text[], array['rest-apis', 'sql', 'problem-solving', 'communication']::text[], array['writing', 'stakeholder-management']::text[], '{}'::int[]),
  ('jd-data-startup', 'Software Engineer (Java/Python)', null, 'full_time', 'software-engineer', 'Entry level (0-3 years)', 'Bachelor''s or Master''s in Computer Science, Software Engineering or related', null, 'Build software in Java and Python at a fast-paced start-up working with data platforms and clients.', '{}'::text[], array['Bachelor''s or Master''s in Computer Science, Software Engineering or related', '0-3 years of software development experience', 'Proficiency in Java and Python with good development practices', 'Experience interacting with REST APIs', 'Strong problem-solving and debugging skills', 'Excellent written and verbal communication']::text[], array['JavaScript, TypeScript and/or React', 'Databricks and Apache Spark', 'Client-facing experience', 'Git', 'Cloud platforms (AWS preferred) and IaC tools (e.g. Terraform)', 'Study or knowledge of economics or finance']::text[], array['java', 'python', 'rest-apis', 'problem-solving', 'communication']::text[], array['typescript', 'react', 'spark', 'git', 'aws', 'terraform', 'stakeholder-management']::text[], '{}'::int[]),
  ('jd-web-agency', 'Web Developer (WordPress/React)', null, 'full_time', 'frontend-developer', null, null, null, 'Build and maintain websites across front and back end using WordPress, React and PHP.', '{}'::text[], array['Experience with WordPress, HTML, CSS, JavaScript, React.js and PHP', 'Ability to troubleshoot front-end and back-end issues independently', 'High attention to detail and strong problem-solving', 'Clear communication and teamwork', 'Strong organisation and time management', 'Full Australian work rights']::text[], array['Experience with Zapier and API integrations']::text[], array['html-css', 'javascript', 'react', 'problem-solving']::text[], array['rest-apis']::text[], '{}'::int[]),
  ('jd-mining-saas', 'Software Engineer (ASP.NET Core/Angular)', null, 'full_time', 'software-engineer', null, 'Tertiary qualification in Computer Science, Software Engineering or related, or equivalent experience', null, 'Turn high-level requirements into production software for mining and field operations on an ASP.NET Core, Angular, MS SQL and mobile stack.', '{}'::text[], array['Strong software engineering fundamentals and production software experience', 'Ability to turn high-level or incomplete requirements into working solutions', 'Ability to understand unfamiliar systems and solve problems independently', 'Strong communication across technical and non-technical stakeholders', 'Experience with AI-assisted development tools, or ability to adopt them quickly', 'Tertiary qualification in Computer Science, Software Engineering or related, or equivalent experience']::text[], array['Experience in mining, field operations or industrial sectors', 'ASP.NET Core, Angular/TypeScript, MS SQL, cloud and mobile experience', 'Startup or SaaS experience']::text[], array['software-engineering', 'problem-solving', 'communication', 'genai']::text[], array['csharp', 'typescript', 'sql', 'mobile-dev']::text[], '{}'::int[]),
  ('jd-business-software', 'Software Developer (C#/Java)', null, 'full_time', 'software-engineer', null, 'Bachelor''s in Software Engineering, Computer Science or related', null, 'Develop and document business software in C#, Java and SQL, working directly with users.', '{}'::text[], array['Proficient in SQL', 'Proficient in C# and Java', 'Strong analytical and problem-solving skills', 'Strong written and verbal communication', 'Ability to communicate with users and document technical solutions', 'Australian work rights']::text[], array['Bachelor''s in Software Engineering, Computer Science or related']::text[], array['sql', 'csharp', 'java', 'problem-solving', 'communication']::text[], array['writing']::text[], '{}'::int[]),
  ('jd-data-platform', 'Backend & Data Engineer (Go/Python)', null, 'full_time', 'data-engineer', null, null, null, 'Build backend services and ETL/ELT pipelines in Go and Python on ClickHouse, with cloud-native deployment and AI integrations.', '{}'::text[], array['Strong Go and Python development', 'Advanced SQL and database design', 'Commercial ClickHouse experience and complex query optimisation', 'Designing ETL/ELT data pipelines', 'Backend architecture and distributed systems', 'dbt and Airflow', 'Docker and Kubernetes', 'CI/CD on GitHub and automated deployment', 'API development and microservice architecture', 'Familiarity with MCP servers and AI integration platforms', 'Strong communication and documentation']::text[], '{}'::text[], array['go', 'python', 'sql', 'databases', 'data-engineering', 'system-design', 'docker', 'kubernetes', 'ci-cd']::text[], array['genai', 'writing']::text[], '{}'::int[]),
  ('jd-fullstack-cloud', 'Full-Stack Engineer (TypeScript/Java)', null, 'full_time', 'software-engineer', 'Experienced', null, null, 'Build secure, scalable full-stack applications with TypeScript/React and Java/Kotlin/Node.js on AWS, using event-driven microservices and AI coding assistants.', '{}'::text[], array['Proven experience in a relevant technical domain', 'TypeScript, React (React Native ideal), state management and frontend build tooling', 'Java, Kotlin, Node.js and frameworks such as Spring Boot or Express', 'RESTful API design, OpenAPI/Swagger and GraphQL', 'Design patterns, refactoring and unit/integration testing', 'AWS, Docker, microservices, event-driven architecture and Kafka', 'Relational and non-relational databases, IaC, CI/CD, observability and Git', 'Confident use of AI coding assistants and ability to evaluate AI-generated code']::text[], '{}'::text[], array['typescript', 'react', 'java', 'nodejs', 'rest-apis', 'aws', 'docker', 'system-design', 'ci-cd', 'genai']::text[], array['mobile-dev', 'nosql', 'terraform', 'git']::text[], '{}'::int[]),
  ('jd-healthtech-software', 'Software Developer', null, 'full_time', 'software-engineer', null, 'Bachelor''s in Computer Science, Software Engineering, IT or related', null, 'Develop reliable web applications using modern object-oriented languages, with exposure to healthcare and medical technology.', '{}'::text[], array['Bachelor''s in Computer Science, Software Engineering, IT or related', 'Commercial software development experience', 'Strong object-oriented programming principles', 'Experience with C#, .NET, Java, Python, JavaScript or similar', 'Understanding of web application development', 'Familiarity with Git', 'Strong problem-solving, communication and collaboration']::text[], array['.NET and C#', 'Vue.js, React or Angular', 'TypeScript', 'REST APIs and microservices', 'Azure, AWS or Google Cloud', 'SQL and relational databases', 'Docker', 'Automated testing', 'CI/CD pipelines', 'Healthcare or medical technology']::text[], array['software-engineering', 'git', 'problem-solving', 'communication']::text[], array['csharp', 'react', 'typescript', 'rest-apis', 'sql', 'docker', 'ci-cd', 'azure']::text[], '{}'::int[]),
  ('jd-web-platform', 'Software Developer (PostgreSQL/AWS)', null, 'full_time', 'software-engineer', null, null, null, 'Build and support secure, scalable web applications and REST APIs on AWS and PostgreSQL within a professional development team.', '{}'::text[], array['Commercial experience as a Software Developer', 'Strong fundamentals: data structures, algorithms and relational databases', 'Object-oriented programming and modern web frameworks', 'Solid SQL, ideally PostgreSQL', 'Building secure, scalable applications and REST APIs', 'Git, automated testing, code reviews and CI/CD', 'Cloud-hosted applications and containers (AWS, Docker)', 'Exposure to AI-assisted tools such as GitHub Copilot or Claude Code', 'Excellent problem-solving and communication']::text[], '{}'::text[], array['algorithms', 'sql', 'rest-apis', 'git', 'ci-cd', 'aws', 'docker', 'software-engineering']::text[], array['genai']::text[], '{}'::int[]),
  ('jd-enterprise-java', 'Full-Stack Developer (Java/Spring/React)', null, 'full_time', 'software-engineer', null, 'Bachelor''s in Computer Science, Information Systems or related', null, 'Build enterprise applications with Spring Boot and React/Next.js, integrating legacy systems on Azure and AWS.', '{}'::text[], array['Java, TypeScript, JavaScript and SQL', 'Spring Boot, Spring Security, Hibernate, Node.js, REST and SOAP services, JUnit, Swagger/OpenAPI', 'React, Next.js (App Router), Tailwind CSS and SSR/SSG/CSR strategies', 'Azure, AWS, CI/CD (Jenkins, Bitbucket Pipelines, Azure Pipelines), OpenShift and Git', 'SQL Server, Azure SQL, MySQL and exposure to vector databases', 'Security: RBAC, CSRF protection and secure session management', 'API contract design, modular backend design, BFF pattern and legacy integration', 'Bachelor''s in Computer Science, Information Systems or related']::text[], '{}'::text[], array['java', 'typescript', 'javascript', 'sql', 'react', 'rest-apis', 'ci-cd', 'git']::text[], array['html-css', 'nodejs', 'azure', 'aws', 'cybersecurity', 'system-design']::text[], '{}'::int[]),
  ('jd-microsoft-partner', 'Software Engineer (.NET/Dynamics 365)', null, 'full_time', 'software-engineer', null, 'Degree in Computer Science, IT or related', null, 'Deliver solutions on Microsoft technologies including Dynamics 365, Power Platform and Azure, using .NET and C# in an Agile DevOps team.', '{}'::text[], array['Degree in Computer Science, IT or related', 'Commercial experience as a Software Engineer or Developer', 'Experience with Dynamics 365, Power Platform, Azure services and/or integration platforms', 'Strong .NET, C#, APIs and SQL', 'Agile, DevOps and CI/CD delivery', 'Clear communication with a broad range of stakeholders']::text[], '{}'::text[], array['csharp', 'sql', 'rest-apis', 'azure', 'agile', 'ci-cd', 'communication']::text[], array['stakeholder-management']::text[], '{}'::int[])
) as j(slug, title, location, job_type, career_id, experience_level, education, salary, description,
       responsibilities, requirements, preferred, required_skills, preferred_skills, grad_years)
join public.companies c on c.slug = j.slug;
