-- Practice bank expansion: data science, system design and behavioural
-- interview questions. Original content written for Career Lighthouse.
insert into public.practice_questions (id, category, difficulty, question, answer, tags, sort) values
  ($q$data-science-01$q$, $q$data-science$q$, $q$basic$q$, $q$Explain the difference between correlation and causation. Why does the distinction matter in product analytics?$q$, $q$- Correlation means two variables move together; causation means changing one actually changes the other. Confounders, reverse causality and selection effects can all produce correlation without any causal link.
- This matters constantly in product analytics: users who enable a feature may retain better because engaged users enable features, not because the feature drives retention.
- To move toward causal claims, use randomised experiments where possible, or quasi-experimental methods and careful cohort comparisons where you cannot randomise.
Tip: Give a concrete product example rather than the textbook ice-cream-and-drowning one; it shows you have worked with real data.$q$, array[$q$statistics$q$, $q$causation$q$]::text[], 10),
  ($q$data-science-02$q$, $q$data-science$q$, $q$basic$q$, $q$What is a p-value, and what are the most common ways it gets misinterpreted?$q$, $q$- A p-value is the probability of observing a result at least as extreme as the one you saw, assuming the null hypothesis is true.
- It does not tell you the probability that the null hypothesis is true, the probability the result will replicate, or the size or business importance of the effect.
- A tiny p-value on a huge sample can accompany a practically meaningless effect, so always pair it with an effect size and a confidence interval.
Tip: Interviewers often probe the misreading that p equals 0.03 means a 97 percent chance the effect is real; correcting that cleanly is a strong signal.$q$, array[$q$statistics$q$, $q$hypothesis-testing$q$]::text[], 20),
  ($q$data-science-03$q$, $q$data-science$q$, $q$basic$q$, $q$In SQL, what is the difference between WHERE and HAVING, and when would you use each in an analytics query?$q$, $q$- WHERE filters individual rows before any grouping happens; HAVING filters groups after GROUP BY and aggregation have run.
- Use WHERE for row-level conditions like date ranges or user segments, and HAVING for conditions on aggregates, such as keeping only customers with more than five orders.
- Filtering early with WHERE is usually cheaper because the database aggregates fewer rows, so never push a row-level condition into HAVING when it belongs in WHERE.
Tip: Be ready to write a quick example on the spot, such as monthly revenue per customer filtered with HAVING SUM(amount) > 1000; short live snippets land well in interviews.$q$, array[$q$sql$q$, $q$aggregation$q$]::text[], 30),
  ($q$data-science-04$q$, $q$data-science$q$, $q$basic$q$, $q$What separates a good product metric from a vanity metric? Give an example of each.$q$, $q$- A good metric is tied to real user or business value, moves when the underlying behaviour changes, and is something the team can act on. A vanity metric goes up and to the right without telling you whether anything improved.
- Cumulative registered users is a classic vanity metric; weekly active users completing a core action, or retention at day 28, are actionable alternatives.
- Good metrics also need a precise definition, a clear owner, and guardrail metrics alongside them so they are hard to game.
Tip: Anchor your example in a product you actually know; interviewers want to hear how you would instrument and sanity-check the metric, not just name one.$q$, array[$q$metrics$q$, $q$product-analytics$q$]::text[], 40),
  ($q$data-science-05$q$, $q$data-science$q$, $q$intermediate$q$, $q$How do you decide how many users you need and how long to run an A/B test?$q$, $q$- Start from a power calculation: pick the minimum detectable effect that would justify shipping, a significance level (commonly 0.05) and power (commonly 0.8), then derive sample size from the metric's baseline and variance.
- Convert that sample size into a duration using expected traffic, and run for whole weeks so day-of-week effects average out.
- Fix the duration in advance; stopping the moment the result looks significant inflates false positives through peeking.
Tip: Mention that halving the minimum detectable effect roughly quadruples the required sample; it shows you have actually run the numbers, not just memorised the formula.$q$, array[$q$ab-testing$q$, $q$experiment-design$q$, $q$statistics$q$]::text[], 50),
  ($q$data-science-06$q$, $q$data-science$q$, $q$intermediate$q$, $q$An A/B test showed a significant uplift, but the metric fell after full launch. How would you investigate?$q$, $q$- Rule out mechanics first: was the launch population the same as the test population, did instrumentation or the metric definition change, and is the drop within normal seasonal variation?
- Consider novelty effects: uplift driven by curiosity often decays, which a longer test or a post-launch holdback group would have revealed.
- Check for winner's curse: when many experiments run, the ones that clear significance tend to overstate their true effect, so the launch estimate was probably optimistic.
- Where possible, keep a small holdout after launch so long-term effects can be measured directly.
Tip: Interviewers reward structured triage, data quality first, then population, then statistics, over jumping straight to one clever explanation.$q$, array[$q$ab-testing$q$, $q$experimentation$q$, $q$debugging$q$]::text[], 60),
  ($q$data-science-07$q$, $q$data-science$q$, $q$intermediate$q$, $q$How would you calculate month-over-month revenue growth in SQL? Talk through your approach and edge cases.$q$, $q$- Aggregate first: group revenue by month using DATE_TRUNC inside a CTE so you have one row per month.
- Then use the LAG window function ordered by month to pull the previous month's revenue onto each row, and compute (current minus previous) divided by previous as the growth rate.
- Handle the edge cases: the first month has no prior value so LAG returns NULL, a zero prior month needs NULLIF to avoid division by zero, and months with no sales vanish entirely unless you join to a calendar or date spine table.
Tip: Raising the NULL and zero handling unprompted is what separates a practised analyst from someone reciting window function syntax.$q$, array[$q$sql$q$, $q$window-functions$q$]::text[], 70),
  ($q$data-science-08$q$, $q$data-science$q$, $q$intermediate$q$, $q$You load a dataset in pandas and find 20 percent of a key column is missing. How do you decide what to do?$q$, $q$- Diagnose before fixing: check whether the missingness is random or systematic by comparing rows with and without the value across other columns and over time; a broken pipeline or a form change often explains a block of NULLs.
- Choose a treatment that fits the analysis: drop rows if data is missing at random and the sample stays large enough, impute with medians or group-level values when the structure supports it, or add an explicit missing-indicator flag for models.
- Document the choice and rerun key results under an alternative treatment to confirm your conclusions are not sensitive to it.
Tip: Saying you would first ask why the data is missing, before naming any fillna strategy, is exactly what interviewers listen for.$q$, array[$q$pandas$q$, $q$data-cleaning$q$]::text[], 80),
  ($q$data-science-09$q$, $q$data-science$q$, $q$intermediate$q$, $q$How do you present an analysis with an uncertain or unwelcome conclusion to non-technical stakeholders?$q$, $q$- Lead with the decision-relevant conclusion in plain language, then state the strength of evidence: what you are confident in, what is uncertain, and what would resolve the uncertainty.
- Translate statistics into business terms: a range of revenue impact rather than a confidence interval, and one clear chart per point rather than a wall of exhibits.
- Separate observations from recommendations, and pre-empt the hardest question by showing you already tested the obvious alternative explanations.
- Never bury an unwelcome result; pairing it with options for how to respond keeps the room constructive rather than defensive.
Tip: Rehearse the one-sentence summary you would give an executive in a lift; if you cannot say it in one sentence, the story is not ready.$q$, array[$q$communication$q$, $q$storytelling$q$]::text[], 90),
  ($q$data-science-10$q$, $q$data-science$q$, $q$intermediate$q$, $q$You built a churn model for a subscription product. Which evaluation metrics would you use and why?$q$, $q$- Accuracy misleads on imbalanced data: if 5 percent of users churn, predicting that nobody churns is 95 percent accurate and completely useless.
- Derive metrics from the intervention: precision matters when retention offers are expensive, recall matters when losing a customer costs far more than a wasted offer, and precision at the top k scored users maps directly to a campaign with a fixed budget.
- Also check calibration if the scores feed revenue forecasts, and evaluate on a time-based holdout, because random splits leak future behaviour into training.
Tip: Framing metric choice around what the business will do with the predictions is what distinguishes an analytics answer from a textbook machine learning answer.$q$, array[$q$model-evaluation$q$, $q$churn$q$, $q$metrics$q$]::text[], 100),
  ($q$data-science-11$q$, $q$data-science$q$, $q$advanced$q$, $q$You are testing a change in a two-sided marketplace. Why can a standard A/B test mislead, and how would you design around it?$q$, $q$- Standard A/B tests assume one user's treatment does not affect another's outcome. In a marketplace, treated buyers compete with control buyers for the same sellers and inventory, so the control group is contaminated and effects get overstated or distorted.
- Design around the interference: randomise by cluster, such as city or category, so interacting units share a treatment, or use switchback tests that alternate the whole market between treatment and control over time.
- These designs shrink the effective sample size, so power calculations must count clusters or time blocks rather than users, and you should quantify the likely bias if you fall back to user-level randomisation.
Tip: Naming the violated assumption, SUTVA, briefly and in plain words shows depth without jargon-dropping.$q$, array[$q$ab-testing$q$, $q$experiment-design$q$, $q$marketplaces$q$]::text[], 110),
  ($q$data-science-12$q$, $q$data-science$q$, $q$advanced$q$, $q$What is Simpson's paradox? Give an example of how it could mislead a business dashboard.$q$, $q$- Simpson's paradox occurs when a trend in aggregated data reverses or disappears once you split by a confounding subgroup, because changing group sizes shift the weighted average.
- Example: overall conversion rises quarter on quarter even though conversion fell in every individual channel, simply because traffic mix shifted toward a high-converting channel. A dashboard showing only the topline would celebrate a genuine decline.
- Guard against it by identifying the segmentations that matter, such as channel, platform and cohort, reviewing key metrics at both levels, and decomposing movements into mix effects versus rate effects.
Tip: Memorise one crisp numeric example with two segments; being able to sketch it on a whiteboard in under a minute is very persuasive.$q$, array[$q$statistics$q$, $q$dashboards$q$]::text[], 120),
  ($q$data-science-13$q$, $q$data-science$q$, $q$advanced$q$, $q$A feature shipped to everyone at once, so there is no control group. How would you estimate its impact?$q$, $q$- Look for a natural comparison: difference-in-differences against a market or platform that did not get the feature, comparing the change in the treated group with the change in the comparison group, after checking that pre-launch trends were parallel.
- With no comparison group at all, use an interrupted time series: model the pre-launch trend and seasonality, forecast the counterfactual, and treat the gap between forecast and actual as the estimated effect.
- Be explicit about threats: concurrent launches, marketing pushes and seasonality can all masquerade as impact, so state your assumptions and report a range rather than a single number.
Tip: Closing with the observation that next time you would ship with a small holdback shows you think about measurement before launch, not after.$q$, array[$q$causal-inference$q$, $q$statistics$q$]::text[], 130),
  ($q$system-design-01$q$, $q$system-design$q$, $q$basic$q$, $q$How would you design a URL shortener that turns long links into short codes and redirects users at low latency?$q$, $q$- Store a mapping from short code to original URL in a key-value store; generate codes by base62-encoding an auto-incrementing ID, which guarantees uniqueness without collision checks.
- Redirects are extremely read-heavy, so put a cache in front of the database so popular links resolve without a database hit.
- Use an HTTP 301 or 302 redirect; choose 302 when you want the browser to keep hitting your server so you can record click analytics.
Tip: Open with a quick estimate of read versus write volume; it shows the interviewer you size systems before drawing boxes.$q$, array[$q$hashing$q$, $q$caching$q$, $q$storage$q$]::text[], 10),
  ($q$system-design-02$q$, $q$system-design$q$, $q$intermediate$q$, $q$Design a rate limiter for a public API. Which algorithm would you choose and where would the counters live?$q$, $q$- Token bucket is a strong default: each client has a bucket that refills at a fixed rate, allowing short bursts while enforcing a long-run average.
- Keep counters in a fast shared store such as an in-memory cache with atomic increments and expiry, so every API server sees the same counts.
- Return HTTP 429 with a Retry-After header so well-behaved clients back off cleanly, and decide whether limits apply per user, per API key, or per IP address.
Tip: Say what happens if the counter store goes down; failing open keeps the API available while failing closed protects the backend.$q$, array[$q$rate-limiting$q$, $q$algorithms$q$, $q$apis$q$]::text[], 20),
  ($q$system-design-03$q$, $q$system-design$q$, $q$intermediate$q$, $q$Design a social news feed. Compare fan-out on write with fan-out on read and explain when each approach wins.$q$, $q$- Fan-out on write pushes each new post into every follower's precomputed feed, so reads are a single fast lookup; it suits accounts with modest follower counts.
- Fan-out on read assembles the feed at request time by pulling recent posts from everyone the user follows; it avoids massive write amplification for celebrity accounts.
- Real systems usually mix both: push for ordinary users, pull for accounts above a follower threshold, then merge the two lists at read time.
Tip: Quantify the trade-off; one post from an account with ten million followers means ten million writes under a pure push model.$q$, array[$q$feeds$q$, $q$fan-out$q$, $q$scalability$q$]::text[], 30),
  ($q$system-design-04$q$, $q$system-design$q$, $q$basic$q$, $q$What problems does a message queue solve in a web backend, and when would you introduce one?$q$, $q$- A queue decouples producers from consumers: the web server enqueues work such as sending an email and responds immediately instead of blocking on a slow downstream task.
- It absorbs traffic spikes, because bursts pile up in the queue and workers drain them at a steady rate, and failed jobs can be retried without being lost.
- Introduce one when a task is slow, failure-prone, or does not need to complete inside the user's request, such as image processing or notifications.
Tip: Mention at-least-once delivery and note that consumers must tolerate duplicate messages, which leads naturally into idempotency.$q$, array[$q$queues$q$, $q$async$q$, $q$decoupling$q$]::text[], 40),
  ($q$system-design-05$q$, $q$system-design$q$, $q$basic$q$, $q$Explain cache-aside caching for a database-backed service and how you would keep cached data from going stale.$q$, $q$- In cache-aside, the application checks the cache first; on a miss it reads the database, writes the result into the cache with a TTL, and returns it.
- Staleness is bounded by the TTL; for stronger freshness, delete or update the cache entry in the same code path that writes the database row.
- Watch for the thundering herd: when a hot key expires, many requests hit the database at once, so use request coalescing or slightly randomised TTLs.
Tip: Invalidation is the hard part of this question, so explain your write path before your read path.$q$, array[$q$caching$q$, $q$invalidation$q$, $q$ttl$q$]::text[], 50),
  ($q$system-design-06$q$, $q$system-design$q$, $q$basic$q$, $q$Your database is overwhelmed by read traffic. What are your options for scaling reads and what trade-offs do they bring?$q$, $q$- Add read replicas: writes go to the primary and replicate to copies that serve queries, multiplying read capacity without major application changes.
- Replication is asynchronous, so replicas lag slightly; a user may not see their own write if the next read hits a replica, so route read-your-own-writes queries to the primary.
- Add a cache for the hottest queries first, since serving repeated reads from memory is often a bigger win than another replica, and consider denormalised read models for expensive joins.
Tip: Name replication lag unprompted; it is the classic follow-up to any read-replica answer.$q$, array[$q$databases$q$, $q$replication$q$, $q$scaling$q$]::text[], 60),
  ($q$system-design-07$q$, $q$system-design$q$, $q$intermediate$q$, $q$Write volume has outgrown a single database primary. How would you shard the data, and what new problems does sharding create?$q$, $q$- Partition rows across multiple databases by a shard key, commonly a hash of the user or tenant ID, so each shard takes a fraction of the write load.
- Choose a key that spreads load evenly and matches your dominant query pattern; queries spanning shards become scatter-gather, and cross-shard transactions get hard.
- Use consistent hashing or a lookup service so new shards can be added without rehashing all existing data.
- Hot keys, such as one very large tenant, can still overload a single shard, so plan for splitting or isolating them.
Tip: State your shard key and justify it before drawing the diagram; the key choice is most of the question.$q$, array[$q$sharding$q$, $q$databases$q$, $q$scaling$q$]::text[], 70),
  ($q$system-design-08$q$, $q$system-design$q$, $q$intermediate$q$, $q$A client may retry a payment request after a timeout. How do you design the API so the charge is applied exactly once?$q$, $q$- Require an idempotency key: the client generates a unique ID for each logical operation and sends the same ID with every retry of that operation.
- The server stores the key alongside the outcome of the first attempt; a retry with the same key returns the stored result instead of charging again.
- Persist the key and the balance change in the same database transaction; if they are written separately, a crash between them recreates the duplicate problem.
Tip: Mention key scope and expiry, per endpoint and per client, which signals you have implemented this rather than only read about it.$q$, array[$q$idempotency$q$, $q$payments$q$, $q$apis$q$]::text[], 80),
  ($q$system-design-09$q$, $q$system-design$q$, $q$basic$q$, $q$You are launching a new backend service. What would you monitor and alert on from day one?$q$, $q$- Track the four golden signals: latency measured as percentiles rather than averages, traffic, error rate, and saturation of CPU, memory, and connection pools.
- Alert on symptoms users actually feel, such as an elevated 5xx rate or p99 latency breaching a target, rather than paging on every internal metric, and write a short runbook for each alert.
- Add structured logs with request IDs so an alert can be traced to specific failing requests, plus health checks on dependencies and a per-service dashboard for on-call use.
Tip: Say p99, not average, early; averages hide the slow tail that pages you at night.$q$, array[$q$monitoring$q$, $q$observability$q$, $q$alerting$q$]::text[], 90),
  ($q$system-design-10$q$, $q$system-design$q$, $q$intermediate$q$, $q$Workers consuming from a queue sometimes fail on certain messages. How do you handle retries without losing or blocking work?$q$, $q$- Retry transient failures with exponential backoff and jitter, and cap the attempt count so one bad message cannot loop forever.
- After the cap is reached, move the message to a dead-letter queue for later inspection, keeping the main queue flowing for healthy work.
- Because queue delivery is at-least-once, make handlers idempotent so a message processed twice does not double its effect.
- Classify failures: poison messages that will always fail should skip retries entirely, while network blips deserve them.
Tip: Alert on dead-letter queue depth; a silently filling DLQ is data loss in slow motion.$q$, array[$q$queues$q$, $q$retries$q$, $q$reliability$q$]::text[], 100),
  ($q$system-design-11$q$, $q$system-design$q$, $q$intermediate$q$, $q$Design a system that recommends jobs to users on a careers platform. Walk through the pipeline from raw data to ranked results.$q$, $q$- Split the problem into candidate generation and ranking: a cheap retrieval step narrows thousands of jobs to a few hundred using embeddings or filters, then a heavier model ranks that shortlist.
- Log user interactions such as views, saves, and applications as training data, and compute user and job features in a feature store shared by training and serving so both see identical values.
- Serve results from a precomputed store refreshed on a schedule, with an optional real-time re-ranking layer when freshness matters.
Tip: Raise the cold-start problem for new users and new jobs, and describe a fallback of popularity plus profile-based matching.$q$, array[$q$ml-systems$q$, $q$recommendations$q$, $q$pipelines$q$]::text[], 110),
  ($q$system-design-12$q$, $q$system-design$q$, $q$advanced$q$, $q$Design a low-latency serving system for a machine learning model that must handle thousands of predictions per second.$q$, $q$- Put the model behind a stateless prediction service that scales horizontally; keep the model in memory and batch concurrent requests to raise hardware throughput.
- Precompute features where possible and fetch the rest from a low-latency feature store, since feature lookup often dominates end-to-end latency rather than inference itself.
- Version every model and roll out with shadow traffic or canaries, comparing live predictions against the incumbent before shifting real traffic.
- Set a latency budget per stage and define a fallback, such as a cached or heuristic response, for when the model misses its deadline.
Tip: Distinguish online inference from batch precomputation; many real-time products actually serve nightly precomputed scores.$q$, array[$q$ml-systems$q$, $q$serving$q$, $q$latency$q$]::text[], 120),
  ($q$system-design-13$q$, $q$system-design$q$, $q$advanced$q$, $q$Your deployed model's accuracy is degrading over time. What could be happening and how would you design monitoring to catch it?$q$, $q$- Suspect data drift, where input distributions change; concept drift, where the relationship between features and outcomes changes; or training-serving skew, where features are computed differently offline and online.
- Monitor input feature distributions against a training baseline, watch the prediction distribution over time, and compute delayed accuracy once true labels arrive.
- Build scheduled retraining on fresh data into the pipeline, with automatic evaluation against a holdout set before any new model is promoted.
- Log the exact feature values used at prediction time so offline analysis can replay requests and pinpoint skew.
Tip: Give a concrete example, such as job market shifts changing which skills predict a successful application.$q$, array[$q$ml-systems$q$, $q$monitoring$q$, $q$drift$q$]::text[], 130),
  ($q$behavioral-01$q$, $q$behavioral$q$, $q$basic$q$, $q$Tell me about yourself.$q$, $q$- Use a present-past-future arc: who you are now (degree, key skills), one or two experiences that prove those skills, then why this role is the logical next step.
- Keep it to 60-90 seconds and tailor every point to the job description instead of reciting your resume chronologically.
- Example sketch: a final-year commerce student highlights their finance major, an internship where they automated a reporting task, and their interest in this graduate analyst program as the natural continuation.
Tip: Script and rehearse the first sentence until it feels natural; a confident opening sets the tone for the whole interview.$q$, array[$q$introduction$q$, $q$communication$q$]::text[], 10),
  ($q$behavioral-02$q$, $q$behavioral$q$, $q$basic$q$, $q$Why do you want to work for this company?$q$, $q$- Show research: name one specific thing that genuinely attracts you, such as a product, a graduate program feature, a recent project or the company's market position.
- Connect it to your own goals: explain what you would contribute and what you hope to learn, so the answer is about mutual fit rather than flattery.
- Avoid generic lines like great culture or big brand unless you can back them with a concrete detail you found yourself.
Tip: Prepare a fresh version for every application; interviewers can spot a recycled answer within seconds.$q$, array[$q$motivation$q$, $q$research$q$, $q$fit$q$]::text[], 20),
  ($q$behavioral-03$q$, $q$behavioral$q$, $q$basic$q$, $q$What are your greatest strengths?$q$, $q$- Pick two or three strengths that match the role's key requirements, and prove each with a short specific example rather than just listing adjectives.
- Structure each one as claim plus evidence: I am strong at X; in situation Y I did Z and the result was W.
- Example sketch: a student claims they learn new tools quickly, then describes mastering a new rostering system within a week at their retail job and training three colleagues to use it.
Tip: Choose strengths a referee would confirm; consistency across your interview, resume and references builds credibility.$q$, array[$q$strengths$q$, $q$self-awareness$q$]::text[], 30),
  ($q$behavioral-04$q$, $q$behavioral$q$, $q$basic$q$, $q$What is your biggest weakness, and what are you doing about it?$q$, $q$- Name a real, work-relevant weakness that is not fatal for the role, then spend most of the answer on the concrete steps you are taking to improve.
- Show evidence of progress: what you changed, what happened as a result, and how you keep yourself accountable now.
- Example sketch: a student who over-polished work and missed internal deadlines now agrees a good-enough checkpoint with teammates and timeboxes each draft, and has hit every milestone since.
- Never claim you have no weaknesses, and avoid the perfectionist cliche delivered as a hidden brag.
Tip: Pick a weakness the interviewer can picture improving, like time management, not one that undermines the core of the job.$q$, array[$q$weaknesses$q$, $q$self-awareness$q$, $q$growth$q$]::text[], 40),
  ($q$behavioral-05$q$, $q$behavioral$q$, $q$intermediate$q$, $q$Tell me about a time you had a conflict with a teammate. How did you handle it?$q$, $q$- Choose a genuine, low-drama disagreement about the work itself, such as approach, priorities or quality standards, and never criticise the other person's character.
- Use STAR with the weight on your actions: you asked for their perspective first, identified the shared goal, and proposed a resolution both sides could accept.
- Example sketch: two members of a group assignment wanted different report structures; you facilitated a short meeting, listed the marking criteria, and agreed a hybrid that lifted the final grade.
- Finish with the outcome and the state of the relationship afterwards; a recovered working relationship impresses more than being proven right.$q$, array[$q$conflict$q$, $q$teamwork$q$, $q$star$q$]::text[], 50),
  ($q$behavioral-06$q$, $q$behavioral$q$, $q$intermediate$q$, $q$Tell me about a time you failed at something. What did you learn?$q$, $q$- Pick a real failure with genuine stakes where you were clearly responsible, not a disguised success or somebody else's mistake.
- Follow a clear arc: brief context, what went wrong and your part in it, how you limited the damage, then the lesson and where you have applied it since.
- Example sketch: underestimating the time needed for a capstone component and missing an internal milestone, then introducing weekly progress checks that brought the project back on track.
Tip: The lesson-applied-later section is what interviewers actually score; a failure story without changed behaviour reads as unfinished.$q$, array[$q$failure$q$, $q$resilience$q$, $q$growth$q$]::text[], 60),
  ($q$behavioral-07$q$, $q$behavioral$q$, $q$intermediate$q$, $q$Describe a time you had to deliver quality work under a tight deadline.$q$, $q$- Show a deliberate response to pressure rather than heroics: you re-planned, prioritised the highest-value tasks, communicated early with whoever was affected, and cut scope where sensible.
- Quantify both the constraint and the result; three days instead of two weeks and delivered the core analysis on time beat vague claims of working hard.
- Example sketch: asked to cover extra shifts during exam period, you negotiated a swap, built a strict revision timetable, and still submitted your assignment a day early.
Tip: Close by mentioning what you now do to avoid last-minute crunches; prevention signals more maturity than survival.$q$, array[$q$deadlines$q$, $q$prioritisation$q$, $q$pressure$q$]::text[], 70),
  ($q$behavioral-08$q$, $q$behavioral$q$, $q$intermediate$q$, $q$Tell me about a time you received difficult feedback. How did you respond?$q$, $q$- Demonstrate that you listened without getting defensive, asked clarifying questions to pin down specifics, and thanked the person even though it stung.
- Then show action: the concrete change you made and evidence it worked, such as improved results or better feedback later on.
- Example sketch: a supervisor said your client emails were too long; you studied effective examples, switched to a summary-first format, and were later asked to draft the team's templates.
Tip: Choose feedback about a skill or habit, not your values or integrity, and keep the story recent enough to matter.$q$, array[$q$feedback$q$, $q$coachability$q$, $q$growth$q$]::text[], 80),
  ($q$behavioral-09$q$, $q$behavioral$q$, $q$basic$q$, $q$How would you structure your answer to a behavioural question such as tell me about a time you solved a problem?$q$, $q$- Use STAR: Situation gives one or two sentences of context, Task states your specific responsibility, Action covers the steps you personally took in first person, and Result shows the outcome, quantified where possible.
- Aim for roughly 20 percent situation and task, 60 percent action, 20 percent result; most candidates over-explain context and under-explain what they actually did.
- Close with a one-line reflection on what you learned or would do differently, which turns a story into evidence of growth.
Tip: Prepare five or six flexible stories from study, work, sport or volunteering; each can usually be adapted to several different questions.$q$, array[$q$star$q$, $q$structure$q$, $q$preparation$q$]::text[], 90),
  ($q$behavioral-10$q$, $q$behavioral$q$, $q$intermediate$q$, $q$Describe a time you took ownership of a problem that was not officially your responsibility.$q$, $q$- Choose a moment you volunteered for something nobody owned: an unclaimed problem, a broken process, or a task a teammate dropped.
- Pair initiative with judgement: you flagged it to the right person, proposed a fix, and followed through to a finished outcome instead of just raising the issue.
- Example sketch: noticing a student club's event sign-up spreadsheet kept breaking, you rebuilt it as a simple online form, documented it, and handed it over so it outlived your involvement.
Tip: End with the ripple effect: who else benefited and whether your fix is still in use today.$q$, array[$q$ownership$q$, $q$initiative$q$]::text[], 100),
  ($q$behavioral-11$q$, $q$behavioral$q$, $q$intermediate$q$, $q$Tell me about a time a team member was not pulling their weight. What did you do?$q$, $q$- Lead with empathy rather than blame: you assumed good intent, checked in privately first, and tried to understand the barrier, whether workload, confusion or something personal, before considering escalation.
- Describe practical fixes: re-dividing tasks around strengths, setting smaller checkpoints, or pairing on a difficult piece, with a tutor or manager involved only as a last resort.
- Close with both outcomes: the work was delivered on time, and ideally the teammate re-engaged rather than being pushed out of the group.
Tip: Interviewers are testing empathy and escalation judgement in equal measure; show both, in that order.$q$, array[$q$teamwork$q$, $q$conflict$q$, $q$empathy$q$]::text[], 110),
  ($q$behavioral-12$q$, $q$behavioral$q$, $q$advanced$q$, $q$Describe a time you persuaded others to adopt your approach when you had no formal authority over them.$q$, $q$- Frame persuasion as evidence plus empathy: you understood their objections first, gathered data or built a small proof of concept, and aligned your proposal with what they already cared about.
- Show stakeholder awareness: who you approached first, how you adjusted the message for each audience, and how you shared credit so the change became a group decision.
- Example sketch: convincing a volunteer committee to shift event promotion to a new channel by running a two-week trial and presenting the sign-up numbers side by side.
Tip: Admitting where you adjusted your own position makes the story far more believable than a flawless victory.$q$, array[$q$influence$q$, $q$persuasion$q$, $q$stakeholders$q$]::text[], 120),
  ($q$behavioral-13$q$, $q$behavioral$q$, $q$advanced$q$, $q$Tell me about a time you managed competing priorities from different people and could not satisfy everyone.$q$, $q$- Show a transparent method: you clarified deadlines and impact with each stakeholder, made the trade-offs visible, and let agreed criteria rather than favouritism decide the order.
- Emphasise how you handled the person who lost out: an early, honest conversation with a revised date preserves trust far better than silence and hope.
- Example sketch: juggling a roster change at work, a group assignment deadline and a society event, you negotiated a shift swap, submitted your section early, and delegated the event task with a clear handover.
Tip: Interviewers listen for whether you communicated the trade-off before the deadline, not after it slipped.$q$, array[$q$prioritisation$q$, $q$stakeholders$q$, $q$communication$q$]::text[], 130),
  ($q$product-design-01$q$, $q$product-design$q$, $q$basic$q$, $q$How do you choose and present a portfolio case study in an interview?$q$, $q$- Choose the project where you can defend every decision, not the prettiest one; interviewers probe reasoning, constraints and trade-offs far more than visual polish.
- Structure the walkthrough as a story: the problem and who had it, your specific role, the research that shaped direction, two or three key decisions with the options you rejected, and the outcome with evidence.
- Show at least one messy early iteration and explain what changed it; process credibility beats a highlight reel of final screens.
- Keep it to eight or ten minutes uninterrupted, then invite questions; running long on context is the most common portfolio mistake.
Tip: Rehearse being interrupted; senior designers will jump in at minute two, and your ability to zoom in and out is part of the test.$q$, array[$q$portfolio$q$, $q$storytelling$q$]::text[], 10),
  ($q$product-design-02$q$, $q$product-design$q$, $q$basic$q$, $q$Walk me through your design process from receiving a brief to developer handoff.$q$, $q$- Start by interrogating the brief: the underlying user problem, the business goal, the constraints, and how success will be measured; a well-framed problem statement is the first deliverable.
- Move through discovery and definition: existing research, quick user interviews or data review, then align stakeholders on scope before drawing anything.
- Explore divergently with low-fidelity sketches and flows, test the risky assumptions early with prototypes, then converge on high fidelity using the design system.
- Treat handoff as a conversation, not a file drop: annotated specs, edge cases, empty and error states documented, and staying available while engineers build.
Tip: Present the process as flexible rather than a fixed ritual; interviewers distrust candidates who apply the same five steps to every problem regardless of context.$q$, array[$q$design-process$q$, $q$collaboration$q$]::text[], 20),
  ($q$product-design-03$q$, $q$product-design$q$, $q$basic$q$, $q$What is the difference between UX and UI design, and how do the two work together?$q$, $q$- UX design covers the whole experience: research, information architecture, user flows and whether the product solves the right problem at all; UI design is the visual and interactive layer, including layout, typography, colour and component behaviour.
- They are inseparable in practice: a beautiful interface wrapped around a confusing flow fails, and a logical flow with illegible controls fails just as hard.
- In most Australian product teams one designer does both, so the distinction matters less than knowing which mode you are in and which question you are currently answering.
Tip: Avoid dismissing UI as decoration; explaining how visual hierarchy and affordances do functional work signals that you respect the craft at both levels.$q$, array[$q$ux-fundamentals$q$, $q$ui-design$q$]::text[], 30),
  ($q$product-design-04$q$, $q$product-design$q$, $q$basic$q$, $q$How do you give and receive design critique?$q$, $q$- Receiving: listen fully before responding, ask clarifying questions to find the underlying concern, and separate your identity from the artefact; you are not your mockup.
- Distinguish direction from suggestion: understand the problem the reviewer sees, then decide the solution yourself rather than mechanically applying every comment.
- Giving: anchor feedback to the stated goal and to evidence, describe the problem you observe rather than prescribing your fix, and be specific; the primary action is hard to find beats this feels cluttered.
- Interviews increasingly include a live critique exercise, so practise doing both kindly and precisely under time pressure.
Tip: In a critique exercise, ask what the goals and constraints were before commenting; critiquing without context is the fastest way to fail it.$q$, array[$q$critique$q$, $q$communication$q$]::text[], 40),
  ($q$product-design-05$q$, $q$product-design$q$, $q$intermediate$q$, $q$How do you approach a whiteboard design challenge, such as designing an app for a given scenario?$q$, $q$- Spend the first quarter of the time on questions: who the users are, which problem matters most, the business constraints, and what success looks like; scoping is the actual skill being tested.
- Pick one primary persona and one core job to be done, state your prioritisation out loud, and explicitly park the rest rather than silently ignoring it.
- Sketch the critical flow end to end at low fidelity before polishing any single screen, narrating trade-offs as you go.
- Reserve time to close properly: walk back through the flow, name your weakest assumption, and say what you would test first.
Tip: Interviewers pass candidates who think aloud and scope ruthlessly, and fail candidates who draw a beautiful home screen for the wrong problem.$q$, array[$q$whiteboard-challenge$q$, $q$problem-framing$q$]::text[], 50),
  ($q$product-design-06$q$, $q$product-design$q$, $q$intermediate$q$, $q$How would you plan usability testing when you have very little time and budget?$q$, $q$- Get clear on the riskiest assumptions first; five participants finding task-level problems beats twenty people answering vague preference questions.
- Recruit pragmatically: guerrilla testing with people who match key traits, existing customers via support channels, or remote unmoderated tools; imperfect participants finding real friction still moves the design forward.
- Write task scenarios rather than instructions: show me how you would change your delivery address, never click the profile icon.
- Timebox the loop: test in the morning, synthesise as a team in the afternoon, fix and retest within the week; the velocity of learning matters more than sample size at this stage.
Tip: Say you would state the limitations of a scrappy study when sharing results; honest small research is credible, oversold small research is not.$q$, array[$q$user-research$q$, $q$usability-testing$q$]::text[], 60),
  ($q$product-design-07$q$, $q$product-design$q$, $q$intermediate$q$, $q$What do you actually check when designing for accessibility, and why does it matter beyond compliance?$q$, $q$- The routine checks: colour contrast against WCAG AA, full keyboard navigability, visible focus states, meaningful labels for screen readers, touch targets large enough for limited dexterity, and never encoding information in colour alone.
- Design-stage habits matter more than late audits: readable type scales, error messages tied clearly to their fields, captions for media, and layouts that survive being zoomed to 200 percent.
- Beyond compliance, accessibility is a quality multiplier: captions help commuters, contrast helps anyone in sunlight, plain language helps everyone, and roughly one in five Australians live with disability, so it is simply designing for the real user base.
Tip: Bring one story where an accessibility fix improved the experience for all users; it reframes the topic from checkbox to craft.$q$, array[$q$accessibility$q$, $q$inclusive-design$q$]::text[], 70),
  ($q$product-design-08$q$, $q$product-design$q$, $q$intermediate$q$, $q$A stakeholder insists on a change you believe harms the user experience. How do you handle it?$q$, $q$- Understand before arguing: ask what outcome they are actually driving at; the demand is often a clumsy proxy for a legitimate goal you can satisfy another way.
- Bring evidence rather than opinion: usability findings, analytics, support tickets or a quick test of both versions turn a taste debate into a decision about data.
- Offer alternatives that meet their goal without the damage, and agree on the metric that would settle the question if you still disagree.
- Know when to disagree and commit: not every battle is the hill, and shipping with a measurement plan beats a stalemate every time.
Tip: When this appears as a behavioural question, tell it as a real story with a concrete resolution; hypothetical diplomacy is far less convincing than a scar with a lesson.$q$, array[$q$stakeholders$q$, $q$influence$q$]::text[], 80),
  ($q$product-design-09$q$, $q$product-design$q$, $q$intermediate$q$, $q$What is a design system, and how do you decide whether a component belongs in it?$q$, $q$- A design system is a shared library of tokens, components and usage guidance, plus the governance around it; its job is consistency and speed, not a sticker sheet of pretty parts.
- Promote a pattern into the system when it recurs across products, has stable requirements, and multiple teams would otherwise rebuild it inconsistently; keep one-off experimental patterns local until they prove themselves.
- Every component needs defined states, hovered, focused, disabled, error, loading, plus accessibility behaviour and documented do-and-do-not examples, or it will be misused.
- Contribution matters as much as consumption: a healthy system has a clear path for teams to propose, review and version changes.
Tip: Mention the cost side, that systems need maintenance and can ossify design, to show you have lived with one rather than just read about them.$q$, array[$q$design-systems$q$, $q$governance$q$]::text[], 90),
  ($q$product-design-10$q$, $q$product-design$q$, $q$intermediate$q$, $q$How do you measure whether a design is successful after launch?$q$, $q$- Define success before shipping: one primary metric tied to the design's intent, such as task completion or activation rate, plus guardrails like error rates and support contacts so a win in one place is not a regression elsewhere.
- Combine behavioural data, funnels, drop-off points and time on task, with attitudinal signals such as satisfaction surveys and follow-up usability sessions; numbers tell you what changed, research tells you why.
- Where traffic allows, an A/B test isolates the design's effect; where it does not, compare cohorts before and after and be honest about confounders.
- Report the misses as well as the wins; a designer who audits their own shipped work earns lasting trust.
Tip: Interviewers listen for whether you chose the metric before launch or went hunting for a flattering one afterwards.$q$, array[$q$metrics$q$, $q$product-thinking$q$]::text[], 100),
  ($q$product-design-11$q$, $q$product-design$q$, $q$advanced$q$, $q$Design a rating and review flow for a marketplace where buyers and sellers have conflicting needs. How do you balance them?$q$, $q$- Name the tension explicitly: buyers want candid reviews and fast decisions; sellers want fairness, context and protection from one bad day defining them; the platform needs enough honest volume to keep trust liquid.
- Design mechanisms rather than compromises: structured prompts that make reviews specific, a seller reply channel, time-boxed dispute paths, and review weighting that decays old signals instead of deleting them.
- Decide the priority order and defend it: trust in reviews usually wins, because once buyers stop believing them the marketplace fails for sellers too.
- Prototype the failure cases, review bombing, retaliation and incentivised reviews, because adversarial behaviour is the norm at marketplace scale.
Tip: Strong answers argue from the health of the whole system, not from splitting the difference between the two sides' wishes.$q$, array[$q$marketplace-design$q$, $q$trust$q$]::text[], 110),
  ($q$product-design-12$q$, $q$product-design$q$, $q$advanced$q$, $q$How would you approach redesigning a heavily used product flow without alienating existing users?$q$, $q$- Start with why: a redesign justified by looks dated usually fails; anchor it to measurable friction, changed user needs or technical constraints, and define upfront what must not regress.
- Research current behaviour deeply, including the workarounds and muscle memory power users have built; what looks like clutter is often somebody's daily shortcut.
- Ship progressively: opt-in previews, staged rollouts by cohort, a transition period with both versions available, and in-product explanations of what moved and why.
- Watch both the metrics and the sentiment channels after each stage, and be genuinely willing to roll back; the redesign backlash pattern is well documented across the industry.
Tip: Citing a real example of a redesign that handled the transition well, or badly, shows you learn from shipped history rather than theory.$q$, array[$q$redesign$q$, $q$change-management$q$]::text[], 120),
  ($q$product-design-13$q$, $q$product-design$q$, $q$advanced$q$, $q$How do you design user experiences for AI-powered features, where outputs are probabilistic and sometimes wrong?$q$, $q$- Set expectations honestly: communicate what the feature can and cannot do, show confidence or sources where meaningful, and never present a guess with the visual authority of a fact.
- Design the error paths as first-class flows: easy correction, visible undo, feedback mechanisms that actually improve the system, and graceful fallbacks for when the model declines or fails.
- Keep the user in control: the AI should draft and suggest while people confirm, especially for consequential actions, with autonomy earned progressively as accuracy and trust are demonstrated.
- Prototype with real model outputs rather than idealised copy; polished placeholder text hides exactly the weirdness you need to design for.
Tip: Raising hallucination, bias and over-reliance unprompted signals you treat responsible AI as a design constraint, not somebody else's problem.$q$, array[$q$ai-ux$q$, $q$responsible-design$q$]::text[], 130)
on conflict (id) do update set
  category = excluded.category, difficulty = excluded.difficulty, question = excluded.question,
  answer = excluded.answer, tags = excluded.tags, sort = excluded.sort;
